### ISSUE TITLE
WPS 无法登陆

### ISSUE THREAD

**Issue by wushangwei** [Gentoo-zh/gentoo-zh#1239]
gentoo下的wps其他功能正常，只是账号相关的没法使用，比如点击登陆按钮无反应，请问大家都是这样的吗？

**Comment by microcai** [comment]
@wushangwei 是啊，这些账号有啥用？

**Comment by wushangwei** [comment]
有时候用用云备份、pdf转word什么的233333

**Comment by liangyongxiang** [comment]
@wushangwei @Universebenzene 你那边也是这样吗？

**Comment by Universebenzene** [comment]
@wushangwei Arch这边登录没问题。我前段日子在Gentoo上试登录确实也是有问题的。这个不会也跟non-systemd有关罢？我现在手头没Gentoo电脑，可能要明下午才能确实是不是这毛病

**Comment by wushangwei** [comment]
@Universebenzene 我有个systemd的gentoo，刚才试了一下也是一样的

**Comment by HougeLangley** [comment]
这个很早以前测试过，确实不能登录。

不过有还是会方便很多…比如，你同事发个文档到你微信，你可以用wps转存，后续回家打开wps文件就能方便处理了。

**Comment by Universebenzene** [comment]
@wushangwei 我解决了。是少了个可执行权限。给wpscloudsvr[加上x权限](https://github.com/Universebenzene/benzene-overlay/blob/1beb9fadcd3a3f1d63eb8d5002e6f2848837b4a6/app-office/wps-office/wps-office-11.1.0.10702-r1.ebuild#L147)就搞定

**Comment by wushangwei** [comment]
@Universebenzene 666，亲测有效

**Comment by liangyongxiang** [comment]
@Universebenzene 天苯pr吧
