### ISSUE TITLE
[package request] xunlei

### ISSUE THREAD

**Issue by damon-kwok** [Gentoo-zh/gentoo-zh#1293]
- xunlei(native) for linux:
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=xunlei-bin

**Comment by Universebenzene** [comment]
[我在自己的overlay打过](https://github.com/Universebenzene/benzene-overlay/blob/master/net-misc/xunlei-download/xunlei-download-1.0.0.2.ebuild)

要是精简菊苣们不想加太多overlay的话就抄过来也行

当然我打包比较菜，仅供参考

**Comment by liangyongxiang** [comment]
如果有人想在gentoo-zh里维护就发pr吧。
