### ISSUE TITLE
app-admin/cockpit-234 fails to compile: configure: error: Package requirements (libsystemd >= 235) were not met

### ISSUE THREAD

**Issue by liangyongxiang** [Gentoo-zh/gentoo-zh#1367]
https://bugs.gentoo.org/825794  app-admin/cockpit-234 fails to compile: configure: error: Package requirements (libsystemd >= 235) were not met:

**Comment by liangyongxiang** [comment]
@microcai

**Comment by liuyujielol** [comment]
https://github.com/cockpit-project/cockpit/issues/14565#issuecomment-686903781
> A lot of cockpit assumes systemd -- these days, cockpit.socket/service rely on socket activation not only for the primary cockpit-tls, but also for the secondary cockpit-ws@ instances. At some point, cockpit-ws will drop doing TLS by itself, we only keep that for backwards compatibility now. Also, a lot of the pages talk to systemd APIs for service management.

cockpit 应该算是强依赖于systemd的，官方的overlay测试环境里面没有systemd，构建失败

**Comment by microcai** [comment]
cockpit 不好用, 除了我试用了一下也没让用了. 散了吧....
