### ISSUE TITLE
net-misc/Cloudreve-3.3.2 operates on file that does not exist

### ISSUE THREAD

**Issue by liangyongxiang** [Gentoo-zh/gentoo-zh#1416]
https://bugs.gentoo.org/826214

**Comment by liangyongxiang** [comment]
https://bugs.gentoo.org/826062

**Comment by oatiz** [comment]
这个包官方提供了可执行文件，是否可以迁移到cloudreve-bin包。移掉这个包

**Comment by liangyongxiang** [comment]
> 这个包官方提供了可执行文件，是否可以迁移到cloudreve-bin包。移掉这个包

这是两个事情，如果是你维护的包不想维护了就发个issue，一周后没有人接手维护就扔吧

**Comment by oatiz** [comment]
明白啦，这个包不是我维护的0.0

**Comment by liangyongxiang** [comment]
已经drop了。
