### ISSUE TITLE
=net-misc/baidunetdisk-4.3.0 segfault without LD_LIBRARY_PATH set

### ISSUE THREAD

**Issue by vizv** [Gentoo-zh/gentoo-zh#1513]
Launch baidunetdisk without `LD_LIBRARY_PATH=/opt/baidunetdisk` will result in segfault, some shared objects may not be compatible with current Gentoo packages

**Comment by Universebenzene** [comment]
@vizv 跟 [我自己打的](https://github.com/Universebenzene/benzene-overlay/blob/master/net-misc/baidunetdisk/baidunetdisk-4.3.0.ebuild) 比对了一下好像没什么大区别，我自己是可以跑起来的，会不会是我没开~的原因？

**Comment by vizv** [comment]
> @vizv 跟 [我自己打的](https://github.com/Universebenzene/benzene-overlay/blob/master/net-misc/baidunetdisk/baidunetdisk-4.3.0.ebuild) 比对了一下好像没什么大区别，我自己是可以跑起来的，会不会是我没开~的原因？

苯菊苣好，我也没开 `~amd`，你尝试更新下包再试试？

**Comment by Universebenzene** [comment]
@vizv 我每天都滚系统的啊。这issue本身也是我早上滚过以后才回的，这就奇怪了

**Comment by vizv** [comment]
@Universebenzene gdb 这个 core 的话是这里炸的……但是没有源码：

```
/home/common/桌面/project/kernel/project/src/Main/p2p_interface.cpp
```

**Comment by Universebenzene** [comment]
@vizv 又是没学过的东西……我去Google😷

**Comment by vizv** [comment]
```
$ coredumpctl info 82065
           PID: 82065 (baidunetdisk)
           UID: 1000 (viz)
           GID: 1000 (viz)
        Signal: 11 (SEGV)
     Timestamp: Wed 2021-12-22 11:17:01 CST (11h ago)
  Command Line: /opt/baidunetdisk/baidunetdisk
    Executable: /opt/baidunetdisk/baidunetdisk
 Control Group: /user.slice/user-1000.slice/user@1000.service/app.slice/app-org.kde.konsole-31a01e4c36b14410984e4506cce14141.scope
          Unit: user@1000.service
     User Unit: app-org.kde.konsole-31a01e4c36b14410984e4506cce14141.scope
         Slice: user-1000.slice
     Owner UID: 1000 (viz)
       Boot ID: e6796b7e4847469ba36ed9f07b5f8f5b
    Machine ID: 066ced39f40f426e595f07ff5f3ddea8
      Hostname: victor
       Storage: /var/lib/systemd/coredump/core.baidunetdisk.1000.e6796b7e4847469ba36ed9f07b5f8f5b.82065.1640143021000000.zst (present)
     Disk Size: 8.0M
       Message: Process 82065 (baidunetdisk) of user 1000 dumped core.
```

@Universebenzene 这是  [coredump.zip](https://github.com/microcai/gentoo-zh/files/7763376/coredump.zip), GitHub 不支持上传 zstd 压缩的 coredump，我就用 zip 重新压缩了下

**Comment by Universebenzene** [comment]
@vizv 总不会跟我是OpenRC用户有关系罢😵

**Comment by OriPoin** [comment]
我在systemd的系统上测试过可以

**Comment by liangyongxiang** [comment]
我测试也没有发现问题。

**Comment by vizv** [comment]
为什么只有我…………………………QAQ
今天下午我查一下依赖好了

**Comment by vizv** [comment]
算了……谁遇到了再开吧（
