### ISSUE TITLE
Why Did the linux-tkg-sources Ebuild Get Removed?

### ISSUE THREAD

**Issue by amarz45** [Gentoo-zh/gentoo-zh#1525]
Hello. I think I remember there being a sys-kernel/linux-tkg-sources ebuild in this overlay. It has use flag options for different cpu schedulers, such as BMQ and PDS. However, this ebuild is gone now. Can you please add it back?

**Comment by Universebenzene** [comment]
@HougeLangley 好像Houge菊苣还得把11月初那个声明给外国友人翻译一下 😂

**Comment by HougeLangley** [comment]
> Hello. I think I remember there being a sys-kernel/linux-tkg-sources ebuild in this overlay. It has use flag options for different cpu schedulers, such as BMQ and PDS. However, this ebuild is gone now. Can you please add it back?

Sorry, linux-tkg group used their install.sh to build and install in gentoo. So, I have to cancel this ebuild.
