### ISSUE TITLE
sys-kernel/xanmod-lts-5.15.11-r1: bugs

### ISSUE THREAD

**Issue by UEForce** [Gentoo-zh/gentoo-zh#1549]
当打开"hardened" USE时会报这个错：
"The merge file '/var/tmp/portage/sys-kernel/xanmod-lts-5.15.11-r1/work/linux-config-5.15.11/hardened-base.config' does not exist.  Exit."

所以说，"hardened-base.config"在哪里？
维护者提供的archive里也没有这个文件，是写错了吗？

**Comment by OriPoin** [comment]
这个use没有经过测试，可以改成hardened-amd64.config

**Comment by UEForce** [comment]
> 这个use没有经过测试，可以改成hardened-amd64.config

那这样的话，你也许可以删掉这一行`		merge_configs+=("${LINUX_CONFIG_DIR}"/hardened-base.config)`

**Comment by OriPoin** [comment]
fixed in #1564
