### ISSUE TITLE
github build action 问题记录

### ISSUE THREAD

**Issue by liangyongxiang** [Gentoo-zh/gentoo-zh#1655]
已知问题：https://github.com/microcai/gentoo-zh/pull/1654#issuecomment-1029769220
标记一下问题和可优化项，

1. 全局开 ~amd64 关键字的情况下，可能出现依赖安装了 ::gentoo 仓库下 test 包导致测试失败的情况，跟进留意
2. 可能出现的循环依赖未自动化解决
3. 报错日志/测试结果无额外输出/展示/保存
4. 多个包提交的情况下，未判断是否需要每个包独立测试还是合并测试
5. 针对明显需要桌面环境的包，使用最基础的 stage3 会花太多时间，可以考虑加如判断后改成 stage3-desktop 或者跳过测试

**Comment by bekcpear** [comment]
6. 从长远考虑，是否需要对 USE 组合进行测试，以及是否需要进行 test 测试
7. emerge 测试成功，但是过程中出现的 QA 问题是否需要标记

可以逐步实现

**Comment by liangyongxiang** [comment]
因为性能问题，先放弃了。
