### ISSUE TITLE
Last rites: sys-kernel/*

### ISSUE THREAD

**Issue by liangyongxiang** [Gentoo-zh/gentoo-zh#1690]

**Comment by liangyongxiang** [comment]
如果有人可以接手可以回复。

**Comment by zozx** [comment]
> 如果有人可以接手可以回复。

我接手一下liquorix-sources, 不过更新速度可能没有HougeLangley这么快, 更新之后可能要过一阵子才bump

**Comment by oatiz** [comment]
没人接手xnamod-hybrid的话，我可以作为保底方案接手（ 自己一直在用这个

**Comment by HougeLangley** [comment]
非常感谢大家

**Comment by liangyongxiang** [comment]
基本有人维护了。我关闭这个issue
