### ISSUE TITLE
使用nvchecker检查上游的版本并且和overlay对比，然后发issue提醒

### ISSUE THREAD

**Issue by liangyongxiang** [Gentoo-zh/gentoo-zh#1697]
有人有兴趣么？

**Comment by liangyongxiang** [comment]
ref:
- nvchecker: https://github.com/lilydjwg/nvchecker
- arch-to-nvchecker: https://github.com/felixonmars/archlinux-futils/blob/master/arch-to-nvchecker

**Comment by liuyujielol** [comment]
@liangyongxiang gentoo好像有对应工具叫euscan：https://github.com/iksaif/euscan ，好像 http://packages.gentoo.org/ 的bump提醒就是用这个生成的

**Comment by liangyongxiang** [comment]
@liuyujielol 我看看。

**Comment by liangyongxiang** [comment]
简单看一下，这个工具最后更新是2016年。对各种软件包的支持也不够nvchecker好。

gentoo官方应该是用 repology.org 的数据：https://archives.gentoo.org/gentoo-dev/message/b793f4da5a5b5e20a063ea431500a820

这个网站提供的数据我记得只覆盖了gentoo main tree，例子：https://repology.org/project/fcitx5/versions

nvchecker是直接去上游检查，这样数据应该是最准确的。

**Comment by liuyujielol** [comment]
@liangyongxiang 看了下，好像现在还在维护的fork应该有 https://github.com/voyageur/euscan 和  https://gitlab.com/src_prepare/euscan-ng 两个，不过nvchecker可能确实更好一点

**Comment by liangyongxiang** [comment]
使用portage api的demo
```python
#!/usr/bin/env python3

import portage
p = portage.db[portage.root]["porttree"].dbapi
print(p.cp_list("sys-apps/portage"))
print(p.cp_list("app-i18n/fcitx"))
print(p.cp_list("app-i18n/fcitx5"))
```
```bash
['sys-apps/portage-3.0.18', 'sys-apps/portage-3.0.20-r6', 'sys-apps/portage-3.0.28-r1', 'sys-apps/portage-3.0.29', 'sys-apps/portage-3.0.30-r1', 'sys-apps/portage-9999']
['app-i18n/fcitx-4.2.9.8', 'app-i18n/fcitx-4.2.9.8', 'app-i18n/fcitx-4.9999']
['app-i18n/fcitx5-5.0.13', 'app-i18n/fcitx5-9999']
```

**Comment by liangyongxiang** [comment]
nvchecker demo:
```
cat sample_config.toml
[__config__]
oldver = "old_ver.json"
newver = "new_ver.json"

[fcitx5]
source = "github"
github = "fcitx/fcitx5"
use_latest_tag = true
```
```
nvchecker -c sample_config.toml -k keyfile.toml
```
```
cat new_ver.json
{
  "fcitx5": "5.0.14"
}
```
