### ISSUE TITLE
app-i18n/mozc-9999[fcitx5] fails to build

### ISSUE THREAD

**Issue by 0n-s** [Gentoo-zh/gentoo-zh#1716]
```
git fetch https://github.com/fcitx/mozc +refs/heads/fcitx5:refs/heads/fcitx5
fatal: couldn't find remote ref refs/heads/fcitx5
 * ERROR: app-i18n/mozc-9999::gentoo-zh failed (unpack phase):
 *   Unable to fetch from any of EGIT_REPO_URI
 *
 * Call stack:
 *     ebuild.sh, line  127:  Called src_unpack
 *   environment, line 3574:  Called git-r3_fetch 'https://github.com/fcitx/mozc' 'refs/heads/fcitx5'
 *   environment, line 2256:  Called die
 * The specific snippet of code:
 *       [[ -n ${success} ]] || die "Unable to fetch from any of EGIT_REPO_URI";
 *
```
This seems to be because https://github.com/fcitx/mozc has merged the fcitx5 & fcitx branch into simply the fcitx branch, as the source files for fcitx5 exist within this branch, e.g.: https://github.com/fcitx/mozc/tree/fcitx/src/unix/fcitx5

**Comment by liangyongxiang** [comment]
Hi, @0n-s, can you help test it? 
If you still have problems you can reopen the issue.

**Comment by Universebenzene** [comment]
@liangyongxiang 仔细看看好像还真的会有问题……

**Comment by 0n-s** [comment]
There is a little new problem now, yes:
```
>>> Source unpacked in /var/tmp/portage/app-i18n/mozc-9999/work
>>> Preparing source in /var/tmp/portage/app-i18n/mozc-9999/work/mozc-9999/src ...
coreutils: cannot stat '/var/tmp/portage/app-i18n/mozc-9999/work/fcitx5-mozc/src/unix/fcitx5': No such file or directory
 * ERROR: app-i18n/mozc-9999::gentoo-zh failed (prepare phase):
 *   (no error message)
 *
 * Call stack:
 *     ebuild.sh, line 127:  Called src_prepare
 *   environment, line 3544:  Called die
 * The specific snippet of code:
 *           cp -pr "${WORKDIR}/fcitx5-mozc/src/unix/fcitx5" unix || die;
```

**Comment by Universebenzene** [comment]
@0n-s Yeah, I realized this just now. Just wait a moment

**Comment by 0n-s** [comment]
That part works now (TYVM for the quick fix!), there's just the issue of an outdated patch now:
```
>>> Source unpacked in /var/tmp/portage/app-i18n/mozc-9999/work
>>> Preparing source in /var/tmp/portage/app-i18n/mozc-9999/work/mozc-9999/src ...
 * Applying mozc-2.26.4220-system_abseil-cpp.patch ...
patching file src/base/absl.gyp
Hunk #1 FAILED at 28.
1 out of 1 hunk FAILED -- saving rejects to file src/base/absl.gyp.rej
patching file src/config/config_test.gyp
Hunk #1 succeeded at 66 with fuzz 2 (offset 30 lines).
Hunk #2 succeeded at 82 (offset 1 line).
patching file src/gyp/common.gypi
patching file src/gyp/common_win.gypi
patching file src/gyp/defines.gypi
Hunk #1 succeeded at 68 (offset 5 lines).
patching file src/gyp/directories.gypi
patching file src/session/session_test.gyp
Hunk #1 succeeded at 222 (offset 1 line).
patching file src/storage/storage_test.gyp
Hunk #1 succeeded at 42 (offset 1 line).
 [ !! ]
 * ERROR: app-i18n/mozc-9999::gentoo-zh failed (prepare phase):
 *   patch -p1  failed with /var/tmp/portage/app-i18n/mozc-9999/files/mozc-2.26.4220-system_abseil-cpp.patch
 *
 * Call stack:
 *               ebuild.sh, line  127:  Called src_prepare
 *             environment, line 3547:  Called eapply '/var/tmp/portage/app-i18n/mozc-9999/files/mozc-2.26.4220-system_abseil-cpp.patch'
 *             environment, line 1315:  Called _eapply_patch '/var/tmp/portage/app-i18n/mozc-9999/files/mozc-2.26.4220-system_abseil-cpp.patch'
 *             environment, line 1253:  Called __helpers_die 'patch -p1  failed with /var/tmp/portage/app-i18n/mozc-9999/files/mozc-2.26.4220-system_abseil-cpp.patch'
 *   isolated-functions.sh, line  112:  Called die
 * The specific snippet of code:
 *              die "$@"
```
(I'm not sure if patches for -9999 packages not applying is considered a problem due to their inherently volatile nature; please excuse me if it isn't)

**Comment by liangyongxiang** [comment]
> I'm not sure if patches for -9999 packages not applying is considered a problem due to their inherently volatile nature; please excuse me if it isn't

I think it is the problem.
You can pr to fix it or ping @Universebenzene

**Comment by Universebenzene** [comment]
@0n-s Those patches are directly from the main tree. I'm not sure if I can fix them before the main tree does. BTW, why do you use the live version 9999 instead of the normal version?

**Comment by 0n-s** [comment]
The patches don't seem like the easiest to rebase (I'll probably have a go at it sometime, though).

As for my reasoning for using mozc-9999, it's mainly because I am using fcitx5-9999 for hopefully improved Wayland support (AFAIK it's still fairly experimental), & I decided to use mozc-9999 as well to match the Fcitx version. Fcitx5 is somewhat new, & even if it wasn't, I wouldn't expect it to maintain a stable IME ABI/API between versions (I'm willing to be corrected on this), so I keep them in sync.
Also, I use [musl](https://wiki.gentoo.org/wiki/Project:Musl) & newer versions of Mozc (for a while now) remove its mutex functionality that need a little patching to work on musl. It's [not much](https://clbin.com/heHYN)[1], but it would be a little cleaner to have it build OOTB.

[1] Please do not import this patch, if it wasn't obvious enough that it's a hackpatch, even if this'll result in functionally equivalent code.

**Comment by liangyongxiang** [comment]
@12101111 韩菊苣有啥建议吗？
