### ISSUE TITLE
drop packages: dev-python/labelme, dev-python/imgviz

### ISSUE THREAD

**Issue by OriPoin** [Gentoo-zh/gentoo-zh#1927]
dev-python/labelme: Image Polygonal Annotation with Python (polygon, rectangle, circle, line, point and image-level flag annotation).
dev-python/imgviz: Image Visualization Tools (object detection, semantic and instance segmentation)

**Comment by liangyongxiang** [comment]
写一下drop的原因？

**Comment by OriPoin** [comment]
因为自己不用这个软件了。
如果有同学在用的话，可以考虑继续维护下去。

**Comment by liangyongxiang** [comment]
嗯嗯，不同的原因 drop 包处理是不一样的。
那我们等一段时间之后，没人接手就drop吧。一周到一个月我觉得都可以。

**Comment by OriPoin** [comment]
目前已经不能用了，要求matplotlib的版本小于3.3，但是main tree的版本最低是3.4
