### ISSUE TITLE
sys-kernel/xanmod-hybrid: K_GENPATCHES_VER do not follow dist-kernel and sys-kernel/gentoo-sources

### ISSUE THREAD

**Issue by OriPoin** [Gentoo-zh/gentoo-zh#2027]
通常 genpatches 会先释出 [tallbar](https://dev.gentoo.org/~mpagano/genpatches/tarballs/) ，可以将这个[项目](https://www.gentoo.org/get-involved/mailing-lists/all-lists.html#:~:text=Java%20on%20Gentoo-,gentoo%2Dkernel,-Release%20announcements%20for)加入邮件列表中，获得最新的资讯。然后过一段时间`dist-kernel`这个项目和`sys-kernel/gentoo-sources`这个包就会使用新鲜的 genpatches 来编译新的内核。通常会有一点小版本上的差异，以`5.17.4`为例， [dist-kernel](https://gitweb.gentoo.org/repo/gentoo.git/tree/sys-kernel/gentoo-kernel/gentoo-kernel-5.17.4.ebuild#n9) 和 [sys-kernel/gentoo-sources](https://gitweb.gentoo.org/repo/gentoo.git/tree/sys-kernel/gentoo-sources/gentoo-sources-5.17.4.ebuild#n7) 就都是 `5.17.6`的 `genpatches`，这个会随着版本的迭代增加。更新版本的时候需要留意一下 main tree 里面的版本，否则会有一些 patch 打不上或者编译不过去的情况。

**Comment by OriPoin** [comment]
@UEForce

**Comment by UEForce** [comment]
@OriPoin 
很抱歉现在才回，这几天没看邮箱和tg。。。
感谢指导orz...还没了解到这个非常惭愧....
修改的版本我已经作为pr提交了。。。

orz...

**Comment by OriPoin** [comment]
[这一行](https://github.com/microcai/gentoo-zh/blob/master/sys-kernel/xanmod-hybrid/xanmod-hybrid-5.15.35.ebuild#L6)也需要改成`38`

**Comment by UEForce** [comment]
> [这一行](https://github.com/microcai/gentoo-zh/blob/master/sys-kernel/xanmod-hybrid/xanmod-hybrid-5.15.35.ebuild#L6)也需要改成`38`

umm，昨天从1到38都测了下，只有K_GENPATCHES_VER=2时才能通过ebuild test.

**Comment by OriPoin** [comment]
> 

需要删掉10开头的linux小版本的pacthes(`KV_MINOR`)，xanmod的pacth是从`KV_MAJOR`开始打的

**Comment by UEForce** [comment]
> 

是的，我昨晚也才搞明白这个。
orz，我五一修，这几天天天考试。

**Comment by UEForce** [comment]
感谢

**Comment by OriPoin** [comment]
@UEForce 不着急，我这几天忙着赶毕设和论文😂
