### ISSUE TITLE
net-misc/postman-bin can be bump to 9.19.0

### ISSUE THREAD

**Issue by geekshen8521** [Gentoo-zh/gentoo-zh#2127]
Currently the version in the repo is `9.6.1`. And according to the [aur](https://aur.archlinux.org/packages/postman-bin), the latest version is `9.19.0`. 

Note that in the ebuild, the SRC link is `https://dl.pstmn.io/download/version/${PV}/linux64`. After testing, the link does not work for versions listed below (may not be complete):
```
9.17.1
9.18.0
9.18.2
9.18.3
```

**Comment by liangyongxiang** [comment]
这个我不确定如何写nvchecker的规则：https://github.com/microcai/gentoo-zh/blob/master/.github/workflows/overlay.toml#L766=

**Comment by liangyongxiang** [comment]
有一些从某个网页里获取版本，例如
```
["net-misc/prips"]
source = "regex"
url = "https://devel.ringlet.net/sysutils/prips/"
regex = "The current version of <strong>prips</strong> is <strong>([\\d.]+)</strong>"
```

或者直接从aur里获取然后调整命名规则也行。你能帮忙加上吗？

**Comment by geekshen8521** [comment]
主要是postman 官网是9.18.3,但是这个无法下载。而最新的测试版是9.20。这个下载就很迷。
我看一下怎么从aur 获取版本信息吧

**Comment by liangyongxiang** [comment]
那这是两个问题，我说的从aur获取是指nvchecker是从aur获取版本信息。

**Comment by geekshen8521** [comment]
@liangyongxiang 

现在大概这样会得到version number： `9.19.0-1`

- 单纯用curl 和jq
```
curl 'https://aur.archlinux.org/rpc/?v=5&type=info&arg[]=postman-bin' -q 2>/dev/null | jq '.results| .[] | .Version'
```

- 用nvchecker 的doc,目前可以变成
```
[postman-bin]
source = "aur"
aur = "postman-bin"
strip_release = 'yes'
```
然后运行`nvchecker -c xxx.toml` 就会得到`[I 05-24 11:57:10.126 core:355] postman-bin: updated to 9.19.0`.
不知道继续要怎么改了

**Comment by liangyongxiang** [comment]
@geekshen8521 那就是把这部分加入到 .github/workflows/overlay.toml 文件里就可以了。

**Comment by liangyongxiang** [comment]
你发pr？

**Comment by geekshen8521** [comment]
我看一下要怎么发pr, 主要是好像要sign off, 我还不太会这个

**Comment by liangyongxiang** [comment]
> 我看一下要怎么发pr, 主要是好像要sign off, 我还不太会这个

main tree才需要。这里不需要。用sign off是好习惯。
