### ISSUE TITLE
app-i18n/libime: ebuild have some mistake.

### ISSUE THREAD

**Issue by HougeLangley** [Gentoo-zh/gentoo-zh#2144]
目前的样子：

![图片](https://user-images.githubusercontent.com/1161594/170328308-ccf9f6b0-41a1-4e52-a814-9e16c032525c.png)

`kenlm.tar.gz` 解压出来到 `src/libime/core/kenlm` 目录以后，应该是在 `src/libime/core/kenlm` 目录下多了一个 `kenlm-${_kenlmcommit} ` 目录的样子，而不是覆盖原有 `src/libime/core/kenlm` 的内容，不知道我这样理解是否正确。

**Comment by RevySR** [comment]
一般来说 SRC_URI描述的压缩包 都会被解压多${WORKDIR}目录
现在可能要确认一下是否link到对应目录比较好

**Comment by liangyongxiang** [comment]
正常来说不应有是这样：https://github.com/fcitx/libime/tree/master/src/libime/core

可以看到 kenlm 是 libime的一个git子模块。更正规的做法是给kenlm再打一个包。其次就是自己下载给定版本的kenlm

**Comment by microcai** [comment]
9999 的话, 应该让 git-r3 自己处理 submodules , 而不是下载个 tar 后替换.

**Comment by microcai** [comment]
已经修正
