### ISSUE TITLE
net-proxy/v2rayA 1.5.7 failed to compile

### ISSUE THREAD

**Issue by wsk2007** [Gentoo-zh/gentoo-zh#2159]
While compiling v2rayA 1.5.7:
 
![image](https://user-images.githubusercontent.com/54563173/170852221-87d1c38e-680b-4bc1-a6c7-e436846d6283.png)

Full build log:
[build.log](https://github.com/microcai/gentoo-zh/files/8792628/build.log)

**Comment by Universebenzene** [comment]
@wsk2007 看来1.5.7这个ebuild真没有一个人能在Gentoo上build成功，等 @liuyujielol 菊苣什么时候上线修罢，感觉最近一直没见他冒泡

**Comment by liangyongxiang** [comment]
@microcai

**Comment by microcai** [comment]
这种 ebuild 还是加个 RESTRICT="primaryuri" 吧. 不然一堆的 404 , 人家mirror说不定把你 ip 给 ban 了

**Comment by microcai** [comment]
@liuyujielol  这个 yarn.eclass 怎么调节下载的 mirror. 默认用 yarnpkg.com 太慢了. 下了几个小时还没下完

**Comment by wsk2007** [comment]
@microcai 貌似按照这个ebuild里的说法，在/etc/portage/mirrors 加一个yarn https://registry.npmmirror.com/ 可以设置镜像

**Comment by microcai** [comment]
@wsk2007 然而毫无作用

**Comment by wsk2007** [comment]
但是我这里从来没有卡过下载，不知道为什么

**Comment by microcai** [comment]
@wsk2007 总之, 我在 manifest 了, 应该很快修好

**Comment by wsk2007** [comment]
@microcai 谢谢

**Comment by microcai** [comment]
姑且算是 好了. 上游把 v2raya@.service 删了

**Comment by wsk2007** [comment]
现在能成功安装了
