### ISSUE TITLE
 Failed to emerge app-i18n/fcitx-9999  The source directory '/var/tmp/portage/app-i18n/fcitx-9999/work/fcitx5-9999' doesn't exist

### ISSUE THREAD

**Issue by not-null-nil** [Gentoo-zh/gentoo-zh#2180]
sudo emerge fcitx-rime

 * IMPORTANT: config file '/etc/portage/package.accept_keywords' needs updating.
 * See the CONFIGURATION FILES and CONFIGURATION FILES UPDATE TOOLS
 * sections of the emerge man page to learn how to update config files.
Calculating dependencies... done!

Verifying ebuild manifests

Emerging (1 of 3) app-i18n/fcitx-9999::gentoo-zh
 * Fetching files in the background.
 * To view fetch progress, run in another terminal:
 * tail -f /var/log/emerge-fetch.log
 * fcitx-data-en_dict-20121020.tar.gz BLAKE2B SHA512 size ;-) ...
Unpacking source...
 * Repository id: fcitx_fcitx5.git
 * To override fetched repository properties, use:
 *   EGIT_OVERRIDE_REPO_FCITX_FCITX5
 *   EGIT_OVERRIDE_BRANCH_FCITX_FCITX5
 *   EGIT_OVERRIDE_COMMIT_FCITX_FCITX5
 *   EGIT_OVERRIDE_COMMIT_DATE_FCITX_FCITX5
 *
 * Fetching https://github.com/fcitx/fcitx5.git ...
git fetch https://github.com/fcitx/fcitx5.git +HEAD:refs/git-r3/HEAD
git symbolic-ref refs/git-r3/app-i18n/fcitx/5/__main__ refs/git-r3/HEAD
 * Checking out https://github.com/fcitx/fcitx5.git to /var/tmp/portage/app-i18n/fcitx-9999/work/fcitx-9999 ...
git checkout --quiet refs/git-r3/HEAD
GIT update -->
   repository:               https://github.com/fcitx/fcitx5.git
   at the commit:            341ae16f36b2851b7dce12b89c870fd24ad44229
Source unpacked in /var/tmp/portage/app-i18n/fcitx-9999/work

> 
> ** ERROR: app-i18n/fcitx-9999::gentoo-zh failed (prepare phase):
>  *   The source directory '/var/tmp/portage/app-i18n/fcitx-9999/work/fcitx5-9999' doesn't exist
>  *
>  * Call stack:
>  *            ebuild.sh, line  770:  Called __ebuild_main 'prepare'
>  *   phase-functions.sh, line 1059:  Called __dyn_prepare
>  *   phase-functions.sh, line  385:  Called die
>  * The specific snippet of code:
>  *              die "The source directory '${S}' doesn't exist"**
>  *
>  * If you need support, post the output of `emerge --info '=app-i18n/fcitx-9999::gentoo-zh'`,
>  * the complete build log and the output of `emerge -pqv '=app-i18n/fcitx-9999::gentoo-zh'`.
>  * The complete build log is located at '/var/tmp/portage/app-i18n/fcitx-9999/temp/build.log'.
>  * The ebuild environment file is located at '/var/tmp/portage/app-i18n/fcitx-9999/temp/environment'.
>  * Working directory: '/var/tmp/portage/app-i18n/fcitx-9999/empty'
>  ** S: '/var/tmp/portage/app-i18n/fcitx-9999/work/fcitx5-9999'**

Failed to emerge app-i18n/fcitx-9999, Log file:

'/var/tmp/portage/app-i18n/fcitx-9999/temp/build.log'

 * Messages for package app-i18n/fcitx-9999:

 * ERROR: app-i18n/fcitx-9999::gentoo-zh failed (prepare phase):
 *   The source directory '/var/tmp/portage/app-i18n/fcitx-9999/work/fcitx5-9999' doesn't exist
 *
 * Call stack:
 *            ebuild.sh, line  770:  Called __ebuild_main 'prepare'
 *   phase-functions.sh, line 1059:  Called __dyn_prepare
 *   phase-functions.sh, line  385:  Called die
 * The specific snippet of code:
 *              die "The source directory '${S}' doesn't exist"
 *
 * If you need support, post the output of `emerge --info '=app-i18n/fcitx-9999::gentoo-zh'`,
 * the complete build log and the output of `emerge -pqv '=app-i18n/fcitx-9999::gentoo-zh'`.
 * The complete build log is located at '/var/tmp/portage/app-i18n/fcitx-9999/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/app-i18n/fcitx-9999/temp/environment'.
 * Working directory: '/var/tmp/portage/app-i18n/fcitx-9999/empty'
 * S: '/var/tmp/portage/app-i18n/fcitx-9999/work/fcitx5-9999'
emerge --info '=app-i18n/fcitx-9999::gentoo-zh
Portage 3.0.30 (python 3.9.12-final-0, default/linux/amd64/17.1/desktop/systemd, gcc-11.3.0, glibc-2.34-r13, 5.15.41-g
=================================================================
                         System Settings
=================================================================
System uname: Linux-5.15.41-gentoo-x86_64-AMD_Ryzen_9_5900HX_with_Radeon_Graphics-with-glibc2.34
KiB Mem:    32335680 total,  31074792 free
KiB Swap:          0 total,         0 free
Timestamp of repository gentoo: Tue, 31 May 2022 09:45:01 +0000
Head commit of repository gentoo: c898c3992bdfe972de236b9fc238d6398883e25e
Timestamp of repository gentoo-zh: Tue, 31 May 2022 10:33:12 +0000
Head commit of repository gentoo-zh: 45ffa5f48203d3ce360c18c2fd7f52083164b234

Timestamp of repository guru: Mon, 30 May 2022 13:03:38 +0000
Head commit of repository guru: fecaa56a41b0bdb407d8dd59fd1a51508037bc5e

Timestamp of repository lisp: Tue, 17 May 2022 03:23:11 +0000
Head commit of repository lisp: ca43dd7c2fe869aa783938f14ecb27227cec4a60

sh bash 5.1_p16
ld GNU ld (Gentoo 2.37_p1 p2) 2.37
app-misc/pax-utils:        1.3.3::gentoo
app-shells/bash:           5.1_p16::gentoo
dev-lang/perl:             5.34.0-r9::gentoo
dev-lang/python:           3.9.12::gentoo, 3.10.4::gentoo
dev-lang/rust-bin:         1.59.0::gentoo
dev-util/cmake:            3.22.4::gentoo
dev-util/meson:            0.61.4-r2::gentoo
sys-apps/baselayout:       2.8::gentoo
sys-apps/sandbox:          2.29::gentoo
sys-apps/systemd:          250.6::gentoo
sys-devel/autoconf:        2.71-r1::gentoo
sys-devel/automake:        1.16.5::gentoo
sys-devel/binutils:        2.37_p1-r2::gentoo
sys-devel/binutils-config: 5.4.1::gentoo
sys-devel/gcc:             11.3.0::gentoo
sys-devel/gcc-config:      2.5-r1::gentoo
sys-devel/libtool:         2.4.6-r6::gentoo
sys-devel/llvm:            13.0.1::gentoo
sys-devel/make:            4.3::gentoo
sys-kernel/linux-headers:  5.15-r3::gentoo (virtual/os-headers)
sys-libs/glibc:            2.34-r13::gentoo
Repositories:

gentoo
    location: /var/db/repos/gentoo
    sync-type: rsync
    sync-uri: rsync://mirrors.tuna.tsinghua.edu.cn/gentoo-portage
    priority: -1000
    sync-rsync-verify-jobs: 1
    sync-rsync-verify-max-age: 24
    sync-rsync-extra-opts:
    sync-rsync-verify-metamanifest: yes

gentoo-zh
    location: /var/db/repos/gentoo-zh
    sync-type: git
    sync-uri: https://github.com/gentoo-mirror/gentoo-zh.git
    masters: gentoo

guru
    location: /var/db/repos/guru
    sync-type: git
    sync-uri: https://github.com/gentoo-mirror/guru.git
    masters: gentoo

lisp
    location: /var/db/repos/lisp
    sync-type: git
    sync-uri: https://github.com/gentoo-mirror/lisp.git
    masters: gentoo

ACCEPT_KEYWORDS="amd64"
ACCEPT_LICENSE="@FREE"
CBUILD="x86_64-pc-linux-gnu"
CFLAGS="-march=znver3 -O2 -pipe"
CHOST="x86_64-pc-linux-gnu"
CONFIG_PROTECT="/etc /usr/share/gnupg/qualified.txt"
CONFIG_PROTECT_MASK="/etc/ca-certificates.conf /etc/dconf /etc/env.d /etc/fonts/fonts.conf /etc/gconf /etc/gentoo-rele
CXXFLAGS="-march=znver3 -O2 -pipe"
DISTDIR="/var/cache/distfiles"
ENV_UNSET="CARGO_HOME DBUS_SESSION_BUS_ADDRESS DISPLAY GOBIN GOPATH PERL5LIB PERL5OPT PERLPREFIX PERL_CORE PERL_MB_OPT
FCFLAGS="-march=znver3 -O2 -pipe"
FEATURES="assume-digests binpkg-docompress binpkg-dostrip binpkg-logs binpkg-multi-instance buildpkg-live config-prote
-logs unmerge-orphans userfetch userpriv usersandbox usersync xattr"
FFLAGS="-march=znver3 -O2 -pipe"
GENTOO_MIRRORS="https://mirrors.tuna.tsinghua.edu.cn/gentoo"
LANG="en_US.utf8"
LDFLAGS="-Wl,-O1 -Wl,--as-needed"
MAKEOPTS="-j17"
PKGDIR="/var/cache/binpkgs"
PORTAGE_CONFIGROOT="/"
PORTAGE_RSYNC_OPTS="--recursive --links --safe-links --perms --times --omit-dir-times --compress --force --whole-file
PORTAGE_TMPDIR="/var/tmp"
SHELL="/bin/zsh"
USE="X a52 aac acl acpi alsa amd64 bluetooth branding bzip2 cairo cdda cdr cli crypt cups dbus dri dts dvd dvdr encode
split-usr ssl startup-notification svg systemd tiff truetype udev udisks unicode upower usb vaapi vdpau vorbis wxwidge
le authz_dbm authz_default authz_groupfile authz_host authz_owner authz_user autoindex cache cgi cgid dav dav_fs dav_l
 sheets words" COLLECTD_PLUGINS="df interface irq load memory rrdtool swap syslog" CPU_FLAGS_X86="mmx mmxext sse sse2"
ubx" INPUT_DEVICES="libinput synaptics" KERNEL="linux" LCD_DEVICES="bayrad cfontz cfontz633 glk hd44780 lb216 lcdm001
N_SINGLE_TARGET="python3_9" PYTHON_TARGETS="python3_9" RUBY_TARGETS="ruby26 ruby27" USERLAND="GNU" VIDEO_CARDS="amdgpu
Unset:  ADDR2LINE, AR, ARFLAGS, AS, ASFLAGS, CC, CCLD, CONFIG_SHELL, CPP, CPPFLAGS, CTARGET, CXX, CXXFILT, ELFEDIT, EM
TAGE_RSYNC_EXTRA_OPTS, RANLIB, READELF, RUSTFLAGS, SIZE, STRINGS, STRIP, YACC, YFLAGS

emerge -pqv '=app-i18n/fcitx-9999::gentoo-zh'
[ebuild  N    ] app-i18n/fcitx-9999  USE="enchant systemd -coverage -doc -presage -test -wayland"

I'm not familiar with ebuild, please help

I have went to `/var/tmp/portage/app-i18n/fcitx-9999/work`, and only saw `fcitx-9999` here.

**Comment by liangyongxiang** [comment]
我晚上找时间处理，需要调整S的值。
