### ISSUE TITLE
Fcitx5与wayland

### ISSUE THREAD

**Issue by ZhaoZuohong** [Gentoo-zh/gentoo-zh#2181]
# 问题描述

1. 全局开启`wayland` USE flag
2. 安装fcitx5
3. 全局关闭`wayland` USE flag并执行`emerge --verbose --ask --deep --changed-use --update @world`
4. 启动Firefox时报错：
```
/usr/lib64/firefox/firefox: symbol lookup error: /usr/lib64/gtk-3.0/3.0.0/immodules/im-fcitx5.so: undefined symbol: gdk_wayland_display_get_type
```

# 暂时的解决方案

重新安装`app-i18n/fcitx-gtk`

**Comment by microcai** [comment]
@ZhaoZuohong 我去, 直接来个 emerge -e world 啊?

**Comment by microcai** [comment]
@microcai 这个是因为 fcitx-gtk 没有 wayland USE flag, 所以 changed-use 没重新编译 fcitx-gtk
