### ISSUE TITLE
net-proxy/Xray无法找到geoip和geosite

### ISSUE THREAD

**Issue by kuppo** [Gentoo-zh/gentoo-zh#2197]
net-proxy/Xray这个包依赖于dev-libs/v2ray-domain-list-community-bin和dev-libs/v2ray-geoip-bin。但这两个包把文件都安装在/usr/share/v2ray路径下。Xray默认寻找geoip的路径是/usr/local/share/xray/，/usr/share/xray/，/opt/share/xray/和xray的安装路径。这个包安装后会出现用找不到geoip.dat和geosite.dat的错误。

可不可以更改xray的ebuild，在安装时自动创建一个soft link到/usr/share/v2ray。
`ln -sn /usr/share/v2ray /usr/share/xray`

我自己的机器上是这么做的，没有问题。

**Comment by liangyongxiang** [comment]
@CHN-beta

**Comment by liangyongxiang** [comment]
也可以sed修改一下路径: https://github.com/XTLS/Xray-core/blob/main/common/platform/others.go#L32=

**Comment by CHN-beta** [comment]
> net-proxy/Xray这个包依赖于dev-libs/v2ray-domain-list-community-bin和dev-libs/v2ray-geoip-bin。但这两个包把文件都安装在/usr/share/v2ray路径下。Xray默认寻找geoip的路径是/usr/local/share/xray/，/usr/share/xray/，/opt/share/xray/和xray的安装路径。这个包安装后会出现用找不到geoip.dat和geosite.dat的错误。
> 
> 可不可以更改xray的ebuild，在安装时自动创建一个soft link到/usr/share/v2ray。 `ln -sn /usr/share/v2ray /usr/share/xray`
> 
> 我自己的机器上是这么做的，没有问题。

谢谢反馈！我其实在service文件中有设置 `XRAY_LOCATION_ASSET=/usr/share/v2ray` 这个环境变量，所以如果用systemd或者openrc启动的话，是可以找到的。但如果手动启动的话，确实会找不到。
我觉得手动建立软链接或许是个好办法。但我觉得，这个软链接由 dev-libs/v2ray-{domain-list-community,geoip}-bin来做会比较好？

**Comment by liangyongxiang** [comment]
> `XRAY_LOCATION_ASSET`

这都不够好，直接sed源码加上合适的路径比较干净。
