### ISSUE TITLE
fcitx now deprecates fcitx-configtool

### ISSUE THREAD

**Issue by amano-kenji** [Gentoo-zh/gentoo-zh#2209]
If you install fcitx now, fcitx package includes fcitx-configtool.

**Comment by liangyongxiang** [comment]
After I `emerge -cv app-i18n/fcitx-configtool`, then run `fcitx5-configtool`, output is:
```
fcitx5-configtool
You're currently running Fcitx with GUI, but fcitx5-config-qt couldn't be found. Now it will open config directory.
Use of uninitialized value $file in open at /usr/lib64/perl5/vendor_perl/5.36/File/MimeInfo/Applications.pm line 140.
Use of uninitialized value $file in open at /usr/lib64/perl5/vendor_perl/5.36/File/MimeInfo/Applications.pm line 140.
Use of uninitialized value in subroutine entry at /usr/lib64/perl5/vendor_perl/5.36/File/BaseDir.pm line 105.
Use of uninitialized value in subroutine entry at /usr/lib64/perl5/vendor_perl/5.36/File/BaseDir.pm line 105.
Use of uninitialized value in subroutine entry at /usr/lib64/perl5/vendor_perl/5.36/File/BaseDir.pm line 105.
No applications found for mimetype: inode/directory
./usr/bin/xdg-open: line 870: x-www-browser: command not found
```

**Comment by amano-kenji** [comment]
Are you sure this is complete? I still can't open fcitx-configtool.

**Comment by liangyongxiang** [comment]
> fcitx package includes fcitx-configtool

After I unmerge fcitx-configtool, then run `fcitx5-configtool` failed.



> Are you sure this is complete? I still can't open fcitx-configtool.

Please show your output of `fcitx5-diagnose` and `fcitx5-configtool`.

**Comment by amano-kenji** [comment]
Never mind. It seems the issue was renaming of fcitx5-configtool to fcitx-configtool led to package collision.

Installing fcitx-configtool again fixed the issue.

**Comment by amano-kenji** [comment]
I advise you against renaming packages. Renaming packages can lead to package collisions.

**Comment by liangyongxiang** [comment]
> I advise you against renaming packages. Renaming packages can lead to package collisions.

The best Gentoo way is to handle the conflict of fcitx:4 and fcitx:5.

But this part needs main tree update, you can see it has been stalled for a long time in this issue: https://bugs.gentoo.org/760501

So we think we don't consider the conflict issue anymore.
