### ISSUE TITLE
sys-kernel/xanmod-hybrid: need successor maintainer

### ISSUE THREAD

**Issue by UEForce** [Gentoo-zh/gentoo-zh#2212]
For personal reasons, I can no longer maintain this package.
If you are willing to take over the maintenance of this package, please reply here.

Please drop sys-kernel/xanmod-hybrid if no one is willing to take over within 14 days. @HougeLangley

**Comment by HougeLangley** [comment]
感谢你的支持，我们等等后续有没有人接手

**Comment by OriPoin** [comment]
我想接手一下，想改成xanmod-sources。
