### ISSUE TITLE
汇总一些很久没有人维护需要bump的老包

### ISSUE THREAD

**Issue by liangyongxiang** [Gentoo-zh/gentoo-zh#2232]

**Comment by liangyongxiang** [comment]
net-proxy/make-proxy ： https://github.com/microcai/gentoo-zh/issues/2107

**Comment by liangyongxiang** [comment]
x11-misc/9menu： https://github.com/microcai/gentoo-zh/issues/2112

**Comment by Linerre** [comment]
dev-util/rust-analyzer: #2095 

guru 里的版本目前是 20220613, 只落后上游一个版本

**Comment by liangyongxiang** [comment]
基于nvchecker，每个包都有单独的issue了
