### ISSUE TITLE
net-dialup/mentohust-9999: Unable to connect to a repository

### ISSUE THREAD

**Issue by liangyongxiang** [Gentoo-zh/gentoo-zh#2378]
log: https://gist.github.com/d0d3e18a4cabb9e32b02372c2ab15e0f

**Comment by Linerre** [comment]
源码似乎随 google code 新网址转到了：https://code.google.com/archive/p/mentohust/downloads

下载了 tar 包，本地 `./configure && make` 是可以编译的， ebuild 可能得改成 `URI_SRC` 的形式

**Comment by liangyongxiang** [comment]
> 源码似乎随 google code 新网址转到了：https://code.google.com/archive/p/mentohust/downloads
> 
> 下载了 tar 包，本地 `./configure && make` 是可以编译的， ebuild 可能得改成 `URI_SRC` 的形式

pr一波？

**Comment by Linerre** [comment]
> pr一波？

我试试
