### ISSUE TITLE
app-text/xdvipdfmx-9999: Unable to connect to a repository

### ISSUE THREAD

**Issue by liangyongxiang** [Gentoo-zh/gentoo-zh#2381]
log : /tmp/portage/app-text/xdvipdfmx-9999/temp/build.log

**Comment by Linerre** [comment]
这个包可以考虑 drop。

首先，它不再作为单独的包来维护了：
>The current version of the package is no longer maintained on CTAN as a separate entity; development now takes place within the TeX Live framework, and it is no longer available as a separate package. For download, support, and other information, please see [TeX Live](https://www.ctan.org/pkg/texlive). However, the information on this page is maintained and should be current. [^1]

[^1]: https://www.ctan.org/pkg/dvipdfmx

其次，main tree 里的 `app-text/texlive-core` 提供了它
```    
 ~ $ e-file xdvipdfmx
 [I] app-text/texlive-core
        Seen Versions:          2017-r4 2019-r10 2019-r11 2019-r4 2019-r7 2019-r8 2020-r1 2020-r10 2020-r11 2020-r12 2020-r3 2020-r4 2020-r5 2020-r6 2020-r7 2020-r8 2020-r9 2021 2021-r1
        Portage Versions:       2021-r1
        Installed Versions:     2021-r1(Fri Aug  5 05:45:58 2022)
        Homepage:               https://tug.org/texlive/
        Description:            A complete TeX distribution
        Matched Files:          /gentoo64/usr/bin/xdvipdfmx; /usr/bin/xdvipdfmx; /usr/src/debug/app-text/texlive-core-2021-r1/texlive-core-2021_build/texk/dvipdfm-x/xdvipdfmx
```
