### ISSUE TITLE
app-emulation/deepin-wine5-5.0.16-r1: No such file or directory

### ISSUE THREAD

**Issue by liangyongxiang** [Gentoo-zh/gentoo-zh#2405]
chmod: cannot access '/tmp/portage/app-emulation/deepin-wine5-5.0.16-r1/image/usr/lib/deepin-wine5/*': No such file or directory

https://gentoo-zh.yongxiang.org/#/builders/2/builds/795

@qsdrqs

**Comment by qsdrqs** [comment]
奇怪，我这里是没有问题的...

我把包先unmerge然后再重新merge才出现这个问题，我发现是因为[113行](https://github.com/qsdrqs/gentoo-zh/blob/15bb2508b39ca28f7300229547798e5721d6fd58/app-emulation/deepin-wine5/deepin-wine5-5.0.16-r1.ebuild#L113)
`fperms 755 /usr/lib/"${PN}"/*`
似乎不支持通配符*，我把他改成
`chmod 755 "${ED}"/usr/lib/"${PN}"/*`
就可以安装成功了。

值得一提的是在安装成功之后就算把那一行改回`fperms 755 /usr/lib/"${PN}"/*`然后重新安装也仍然可以安装成功，不太了解这是什么原因导致的。

我会提一个新pr来修复这个bug
