### ISSUE TITLE
app-i18n/fcitx-5.0.19: [31mFAILED: [0msrc/modules/unicode/CMakeFiles/unicode.dir/charselectdata.cpp.o

### ISSUE THREAD

**Issue by HougeLangley** [Gentoo-zh/gentoo-zh#2495]
完整描述已发到上游：

https://github.com/fcitx/fcitx5/issues/596

**Comment by liuyujielol** [comment]
请问5.0.18能正常编译吗?龙芯的gcc是patch过的吗？还是gcc-13 + glibc-2.36的问题?`charselectdata{.h,.cpp}`在5.0.19里面应该是没有动过的

这个的解决办法应该还是和之前一样，在`charselectdata{.h,.cpp}`里面加`#include <cstdint>`
```
   14 | #include <vector>
  +++ |+#include <cstdint>
   15 |
```

**Comment by HougeLangley** [comment]
Fix https://github.com/fcitx/fcitx5/commit/efdfdf07e4e6ff5502b5c04ee440d7cefa319269

**Comment by liangyongxiang** [comment]
> Fix [fcitx/fcitx5@efdfdf0](https://github.com/fcitx/fcitx5/commit/efdfdf07e4e6ff5502b5c04ee440d7cefa319269)

gentoozh这边处理了么？
