### ISSUE TITLE
fcitx-9999: ln: failed to create symbolic link 'src/modules/spell/dict/en_dict-20121020.tar.gz': No such file or directory

### ISSUE THREAD

**Issue by Allen050329** [Gentoo-zh/gentoo-zh#2532]
The ebuild fails to link ${DISTDIR}/fcitx-data-en_dict-20121020.tar.gz to src/modules/spell/dict/en_dict-20121020.tar.gz for whatever reason

**Comment by Allen050329** [comment]
reason found: no folder named dict in /var/tmp/portage/app-i18n/fcitx-9999/work/fcitx-9999/src/modules/spell

**Comment by Allen050329** [comment]
Also, the downloading mechanism seems broken while being executed by the ebuild

**Comment by liuyujielol** [comment]
merging #2533 should fix this
