### ISSUE TITLE
dev-util/rust-analyzer: now part of dev-lang/rust(>=1.64.0)

### ISSUE THREAD

**Issue by liuyujielol** [Gentoo-zh/gentoo-zh#2542]
main tree的rust-1.64已经有~amd64 keyword了[1]
rust-analyzer已经是dev-lang/rust的一部分了(`>=dev-lang/rust-1.64.0[rust-analyzer]`)
dev-util/rust-analyzer也许该考虑drop掉？

[1]. https://github.com/gentoo/gentoo/commit/0005bfa350426da31f95de02c34c4debec5c1d06

**Comment by liangyongxiang** [comment]
我觉得可以。
