### ISSUE TITLE
about RDEPEND of nvchecker 2.9

### ISSUE THREAD

**Issue by kungkao** [Gentoo-zh/gentoo-zh#2563]
I just found from nvchecker-2.9.ebuild that ">=www-servers/tornado-6" is one of nvchecker 2.9's RDEPEND. 
However, I cannot find "www-servers/tornado" in gentoo-zh repo, nor the official Gentoo repo. 
Instead, "dev-python/tornado" is always there, in the official repo. 
Is this a typo or there is something I don't know?

**Comment by liangyongxiang** [comment]
> Is this a typo or there is something I don't know?

It is renamed in the main tree and needs to be updated in gentoo-zh: https://github.com/gentoo/gentoo/commit/3352113bdd5ee62808ca4ea5f4bb2c6f0f79daf6

**Comment by liangyongxiang** [comment]
@CHN-beta dev-python/python-telegram-bot 也有类似的问题

**Comment by CHN-beta** [comment]
> @CHN-beta dev-python/python-telegram-bot 也有类似的问题

我想要把dev-python/python-telegram-bot drop掉了，因为我看到guru有了，而且维护得还挺勤快的。

**Comment by liangyongxiang** [comment]
> > @CHN-beta dev-python/python-telegram-bot 也有类似的问题
> 
> 我想要把dev-python/python-telegram-bot drop掉了，因为我看到guru有了，而且维护得还挺勤快的。

好的。
