### ISSUE TITLE
v2ray-5.1.0 can not be started by openrc

### ISSUE THREAD

**Issue by kelvin34501** [Gentoo-zh/gentoo-zh#2575]
the init file `v2ray.initd-r1`

This line:
```
--exec /usr/bin/v2ray run -config ${V2_CONFIG}
```
should probably be
```
--exec /usr/bin/v2ray -- run -config ${V2_CONFIG}
```

**Comment by Universebenzene** [comment]
@kelvin34501 Firstly, v2rayA-1.5.9.1698.1 does not support v2ray>5 yet. And we have already limited the version [in the ebuild](https://github.com/microcai/gentoo-zh/blob/master/net-proxy/v2rayA/v2rayA-1.5.9.1698.1.ebuild#L31). I think maybe you installed v2ray-core manually without portage, so I suggest you to downgrade your v2ray-core below version 5 now.


I think those init script will be fix in next upgrade of v2rayA

**Comment by liangyongxiang** [comment]
@liuyujielol
