### ISSUE TITLE
net-proxy/v2ray fails to build (unpack phase)

### ISSUE THREAD

**Issue by liuyujielol** [Gentoo-zh/gentoo-zh#2618]
```
>>> Unpacking source...
>>> Unpacking v2ray-4.45.2.tar.gz to /tmp/portage/net-proxy/v2ray-4.45.2/work
>>> Unpacking v2ray-4.45.2-vendor.tar.gz to /tmp/portage/net-proxy/v2ray-4.45.2/work
go mod verify
go: github.com/cheekybits/genny@v1.0.0: Get "https://proxy.golang.org/github.com/cheekybits/genny/@v/v1.0.0.mod": dial tcp 142.251.42.241:443: connect: network is unreachable
 [31;01m*[0m ERROR: net-proxy/v2ray-4.45.2::gentoo-zh failed (unpack phase):
```

go-module_src_unpack 改了
https://github.com/gentoo/gentoo/commit/733b4944c1a061269f96219cc96530f89d8f439e

**Comment by Universebenzene** [comment]
@liuyujielol 好像iYI菊苣的vendor打包法受影响了…… @bekcpear

**Comment by bekcpear** [comment]
`go mod verify` 会去验证本地 mod cache 的 hash 值，使用 vendor 的话，在 portage 环境下不会有 mod cache，所以会尝试联网下载，而 portage 下默认无网络，所以失败。

解决方法：

1. 使用这个 eclass 内的 deps 包打依赖 或 EGO_SUM 设本地代理
2. 不使用 go-module.eclass

原作者的想法应该是避免 deps 包内容与原 go 包所记录不一致，他是在尝试纠正打包者的错误，私以为没有必要，打包者真想干点啥也挺简单的。

至于采用何种方式解决，由维护者决定。

**Comment by liuyujielol** [comment]
@bekcpear 我就直接覆盖掉了go-module_src_unpack，估计eclass后面还会改，比如改成nonfatal之类的

**Comment by Universebenzene** [comment]
@liuyujielol 暂且在我自己仓库[随便糊了一个](https://github.com/Universebenzene/benzene-overlay/commit/17a99e0e186670495c346e305db27c1ed970597c)，看官方后续还有啥动作罢……

**Comment by Universebenzene** [comment]
等会，这issue怎么就close了，v2ray-4的ebuild根本没修啊

**Comment by liuyujielol** [comment]
原来没有吗....

**Comment by Universebenzene** [comment]
@liuyujielol 4 还是用的 go-module配合iYI菊苣的vendor法，仍然会被go-module里的go mod verify 拦住。5因为用的是官方的deps依赖包所以没事

**Comment by Universebenzene** [comment]
好家伙，这玩意不是官方也修了？  [gentoo/gentoo@b0a4dff](https://github.com/gentoo/gentoo/commit/b0a4dffcac4b7994d1832f69dade037cbabf6997)

昨这issue刚reopen就😂
