### ISSUE TITLE
media-gfx/unityhub does not start

### ISSUE THREAD

**Issue by gekret005** [Gentoo-zh/gentoo-zh#2781]
After installing the ebuild for 3.3.0 it just hangs till I ^c the process when trying to start it. Running ldd on the binary shows that it can find all the libraries. What else can be done to deduce the problem?

**Comment by gekret005** [comment]
Turns out after looking at the logs it was missing app-crypt/libsecret. The ebuild should depend on such.

**Comment by liangyongxiang** [comment]
@ShiinaKagari

**Comment by ShiinaKagari** [comment]
Fixed on version 3.4.1

**Comment by liangyongxiang** [comment]
> Fixed on version 3.4.1

I'm having some problems: https://gentoo-zh.yongxiang.org/#/builders/2/builds/24928/steps/6/logs/stdio

**Comment by liangyongxiang** [comment]
https://github.com/microcai/gentoo-zh/pull/2974
