### ISSUE TITLE
Gentoo-zh 软件包目前现状统计

### ISSUE THREAD

**Issue by HougeLangley** [Gentoo-zh/gentoo-zh#2794]
各位 gentoo-zh 朋友，最近我在编辑一个表格，用于统计我们 gentoo-zh 社区内软件包的维护情况，有兴趣的朋友可以参与编辑，方便后续统计和社区用户认领任务，也方便查看软件包更新维护情况，方便联系原先维护人员，催更和丢弃老包。

[【金山文档】 gentoo-zh软件包现状
](https://kdocs.cn/l/cnNaWqUq7uH9)

**Comment by liangyongxiang** [comment]
没有继续维护更新了。我先关闭issue
