### ISSUE TITLE
x11-themes/fcitx5-breeze missing BDEPEND="media-gfx/inkscape"

### ISSUE THREAD

**Issue by blackteahamburger** [Gentoo-zh/gentoo-zh#2808]
See https://github.com/scratch-er/fcitx5-breeze#build.

**Comment by liangyongxiang** [comment]
@OriPoin

**Comment by OriPoin** [comment]
这个问题是某菊苣提出来的，相关讨论从这里开始[Gentoo-zh](https://t.me/gentoo_zh/222316)
在ebuild中，更改了上游的代码。
个人也觉得没有必要使用inkscape，于是就这样做了，相关PR #2123
目前ebuild确实也出了问题，尽快修

**Comment by OriPoin** [comment]
改出来效果不好，还是使用inkscape吧

**Comment by OriPoin** [comment]
it works on my machine

**Comment by liangyongxiang** [comment]
ping @blackteahamburger

**Comment by liangyongxiang** [comment]
If there are still problems please reopen pr

**Comment by blackteahamburger** [comment]
> ping @blackteahamburger

It works, thanks!
