### ISSUE TITLE
关于目前 app-i18n/sogoupinyin 的问题及讨论

### ISSUE THREAD

**Issue by HougeLangley** [Gentoo-zh/gentoo-zh#2823]
1. 目前提供的下载连接并没有指向 4.0.1.2123，而是指向 2.2.0.0108 版本，并且也无法下载；
2. sogoupinyin 只支持 fcitx4 ，而不支持 fcitx5 ，是否还需要继续维护？
3. 目前版本落后，最新版本 4.0.1.2800

@microcai @Universebenzene @liangyongxiang 

目前包的维护是微菜，大家讨论下是继续 bump 还是 drop ？

**Comment by liangyongxiang** [comment]
@HougeLangley 我觉得可以drop

**Comment by microcai** [comment]
@HougeLangley drop

**Comment by HougeLangley** [comment]
好耶，一秒钟解决~
