### ISSUE TITLE
loongarch 现在二进制都是旧世界 谨慎添加二进制软件

### ISSUE THREAD

**Issue by RevySR** [Gentoo-zh/gentoo-zh#2853]
只有在新世界的的gentoo这边测试通过的软件才可以添加 loong keyword

以下待处理
- [x] https://github.com/microcai/gentoo-zh/blob/6704a34c1a952f22745d6f20c50321d7d17493db/sci-electronics/lceda-pro/lceda-pro-1.9.29.ebuild#L18

**Comment by RevySR** [comment]
@123485k 看一下上述问题 是否在loong 新世界测试过

**Comment by liangyongxiang** [comment]
我的 3A5000 也还没弄桌面，显卡都拔掉了。
我需要年假之后才有硬件测试。

**Comment by 123485k** [comment]
> @123485k 看一下上述问题 是否在loong 新世界测试过

我暂时把loong的keyword去掉，等有人测试通过可用再加上

**Comment by liangyongxiang** [comment]
都清理了。

**Comment by RevySR** [comment]
> 都清理了。

这不是解决 是要挂着直到新旧世界问题结束之后才关闭的

**Comment by xen0n** [comment]
Update:

准备将 `loongson-overlay` 的 `liblol` 打包工作上游至此处，这样会新增一个 `virtual/loong-ow-compat` marker 包可用

这样一来，只要将所有采用 LoongArch 旧世界 ABI 的二进制包，都标记上 `loong? ( virtual/loong-ow-compat )` 的 `RDEPEND`，即可实现：

* 安装旧世界二进制包时，自动将 `liblol` 及其内核模块拉入依赖，
* 区分新、旧世界的 LoongArch 包，
* 当系统上所有旧世界包都消失，`liblol` 将可被自动 depclean

的效果。

Plus it's very much *the Gentoo way* ;-)

**Comment by RevySR** [comment]
补充：
提交必须经过测试才能 `keyword`

**Comment by liangyongxiang** [comment]
这个 issue 需要修改标题或者 重新开一个吗？

**Comment by RevySR** [comment]
> 这个 issue 需要修改标题或者 重新开一个吗？

可以开一个新的
