### ISSUE TITLE
typora-0.11.18 should not be dropped

### ISSUE THREAD

**Issue by Universebenzene** [Gentoo-zh/gentoo-zh#2928]
我上次在 #2758 说过，0.11.18是要专门给免费用户留的版本，不能扔。@microcai 蔡博士你着急了 [deebaa5](https://github.com/microcai/gentoo-zh/commit/deebaa5f4110982487b9c4ccc2ea6fa945ee2b77)

按 #2759 还回去罢

**Comment by microcai** [comment]
@Universebenzene 哦哦哦
