### ISSUE TITLE
[SOLVED]net-im/tencent-qq启动报错，无法使用

### ISSUE THREAD

**Issue by Nuralii1i** [Gentoo-zh/gentoo-zh#3062]
报错内容为：
{"Message":"node-loader:\nError:/opt/QQ/resources/app/libbugly.so:undefined symbol:gnutls_free"}
桌面环境是DWM
profile是[13]  default/linux/amd64/17.1/desktop/systemd/merged-usr (stable) *

**Comment by st0nie** [comment]
@Nuralii1i net-libs/gnutl
掉了这个依赖，我回去加上

**Comment by st0nie** [comment]
@st0nie 暂时请
emerge -a1 net-libs/gnutls解决一下

**Comment by st0nie** [comment]
@st0nie *gnutls

**Comment by Nuralii1i** [comment]
> @st0nie 暂时请 emerge -a1 net-libs/gnutls解决一下

我有这个包了，还是一样打不开，重新安装时有如下提示：
 * QA Notice: Found the following implicit function declarations
in configure logs:
 *   /var/tmp/portage/net-libs/gnutls-3.8.0/work/gnutls-3.8.0-abi_x86_64.amd64/config.log:5070 - MIN
 *   /var/tmp/portage/net-libs/gnutls-3.8.0/work/gnutls-3.8.0-abi_x86_64.amd64/config.log:5853 - static_assert
 *   /var/tmp/portage/net-libs/gnutls-3.8.0/work/gnutls-3.8.0-abi_x86_64.amd64/config.log:9596 - alignof
 * Check that no features were accidentally disabled.
 * See https://wiki.gentoo.org/wiki/Modern_C_porting.
strip: x86_64-pc-linux-gnu-strip --strip-unneeded -N __gentoo_check_ldflags__ -R .comment -R .GCC.command.line -R .note.gnu.gold-version
   /usr/lib64/libgnutlsxx.so.30.0.0
   /usr/lib64/libgnutls-openssl.so.27.0.2
   /usr/lib64/libgnutls.so.30.35.0
太离谱了，群里几个用这个qq的都出过问题，还各不相同

**Comment by Nuralii1i** [comment]
因为profile默认没开启net-libs/gnutls的静态库支持（static-libs),手动加上该USE flag重新编译net-libs/gnutls解决了本issue提到的问题。

**Comment by st0nie** [comment]
@Nuralii1i 无法复现，gnutls不需要static-libs，qq也是可以运行的
