### ISSUE TITLE
CI 里的 git commit 链接错误

### ISSUE THREAD

**Issue by liangyongxiang** [Gentoo-zh/gentoo-zh#3139]
例如 https://github.com/microcai/gentoo-zh/pull/3137 里的 commit 链接是 https://github.com/gentoo-mirror/gentoo/commit/3edcc3c20db79d7656a32f9d8301239bf450dfcf ，实际上main tree 没有这个commit。

原因是因为：https://github.com/microcai/gentoo-zh/commit/043896cbc68e44c709b332327504f3be2017a3c9

我能想到的解决办法是
1. revert 上面的 commit
2. 调整 CI 的获取的 commit 信息：

cc @vowstar

**Comment by bekcpear** [comment]
实际上 portage 本身就没有加载 overlay 下 package.mask 的行为，所以我个人完全不建议手动加载 overlay 下的 package.mask 到 ::gentoo 仓库来避免 pkgcheck 的警告/报错。

如果需要避免这种问题，正确的措施是给 portage 增加对应的功能。

而针对 pkgcheck 的警告/报错，是由仓库的维护者来判定是否忽略，对于 pkgcheck 本身，它应该正确的输出其内容，如果有不对的地方，应该给 pkgcheck 提 issue/pr

至于解决办法1，需要 revert 的是两个 commit： https://github.com/microcai/gentoo-zh/commit/043896cbc68e44c709b332327504f3be2017a3c9 以及 https://github.com/microcai/gentoo-zh/commit/ce9525f6b7bd6fb3d2516eb6aa82acdb9717366d

**Comment by bekcpear** [comment]
如果保持这样的一个行为，甚至会误导仓库的贡献者，认为在 overlay 下的 package.mask 下加入对应的信息可以影响到整体的行为，而实际上 overlay 下的 package.mask 不会有作为，除非选择的是 overlay 下的 profile，但是维护一个额外的 profile 的成本是不低的，而且作用有限。

**Comment by bekcpear** [comment]
相关 bugs:

https://bugs.gentoo.org/641020
https://bugs.gentoo.org/832962

**Comment by vowstar** [comment]
可以revert, 等portage相关功能改进,
代价是这段时间将由仓库的维护者来人工判定pkgcheck 的警告/报错.

pkgcheck的相关issue已在2022年提出, 但是显然这不是pkgcheck的问题, pkgcheck忠实完成了自己的功能, 这依然是portage本身的缺陷:
https://github.com/pkgcore/pkgcheck/issues/402

变通的解决方法有:
https://gitlab.com/Parona/parona-overlay/-/blob/master/metadata/pkgcheck.conf#L3 的例子
代价是no-multilib(如果还有人在用的话)不再被检查.

**Comment by liangyongxiang** [comment]
我比较倾向于人工检查。
