### ISSUE TITLE
[nvchecker] net-proxy/dae can be bump to v0.1.7

### ISSUE THREAD

**Issue by microcai** [Gentoo-zh/gentoo-zh#3175]
oldver: 0.1.7
CC: @st0nie

**Comment by liangyongxiang** [comment]
@peeweep 有bug了？

**Comment by st0nie** [comment]
@liangyongxiang 顺便帮我close 下#3004 #2858 #3072

**Comment by peeweep** [comment]
@liangyongxiang 不是 bug

@st0nie  nvchecker 配置文件里要加 prefix = "v"
