### ISSUE TITLE
media-fonts/sarasa-mono-sc-nerd has migrated to another repo

### ISSUE THREAD

**Issue by xux1217** [Gentoo-zh/gentoo-zh#3178]
this package has migrated, the origin repo is https://github.com/laishulu/Sarasa-Mono-SC-Nerd, and the latest repo is https://github.com/laishulu/Sarasa-Mono-SC-Nerd.

need update the ebuild file.

**Comment by Linerre** [comment]
New upstream: https://github.com/laishulu/Sarasa-Term-SC-Nerd
PR created.
