### ISSUE TITLE
wps media-libs/tiff 依赖冲突

### ISSUE THREAD

**Issue by oopschen** [Gentoo-zh/gentoo-zh#3224]
app-office/wps-office--11.1.0.11698 依赖包media-libs/tiff-compat:4, 系统选择media-libs/tiff-compat-4.4.0-r1版本。
通用软件gimp,imagemagic,wxGTK等均以来media-libs/tiff:0/0,系统选择media-libs/tiff-4.4.0-r2版本。
两个版本冲突，无法安装wps-office。
建议修改wps-office依赖media-libs/tiff:0/0, 本机测试通过。

**Comment by Universebenzene** [comment]
@oopschen tiff-4.4.0-r2这版本早仨月前main tree就已经drop掉了，现在tiff早没有0/0的slot了。你系统多久没滚了？

**Comment by oopschen** [comment]
> @oopschen tiff-4.4.0-r2这版本早仨月前main tree就已经drop掉了，现在tiff早没有0/0的slot了。你系统多久没滚了？

Portage 3.0.44 (python 3.11.3-final-0, default/linux/amd64/17.1/desktop, gcc-12, glibc-2.36-r7, 6.1.19-gentoo x86_64)
=================================================================
System uname: Linux-6.1.19-gentoo-x86_64-Intel-R-_Core-TM-_i7-8550U_CPU_@_1.80GHz-with-glibc2.36
KiB Mem:    16274344 total,  13667892 free
KiB Swap:    8539132 total,   8539132 free
Timestamp of repository gentoo: Tue, 09 May 2023 08:15:01 +0000
Head commit of repository gentoo: ed1f36b65db2f31193609d8c6809bbe9428de5ab
Timestamp of repository gentoo-zh: Tue, 09 May 2023 09:32:02 +0000
Head commit of repository gentoo-zh: b16b5ac442e012368e7441ad7c900ca1e7485508

Timestamp of repository Miezhiko: Sun, 07 May 2023 16:18:21 +0000
Head commit of repository Miezhiko: c72a967aedaaf35b3b473ff23e096acd949ed42d

已经更新过，依然是这个样子。官方的tiff确实已经到4.5.0的版本

**Comment by Universebenzene** [comment]
@oopschen 那应该没问题了啊。你说的那些所谓依赖tiff:0/0的包在4.4.0被drop以后早就应该更新了依赖才对，不可能再出现还有包依赖写tiff:0/0的

**Comment by oopschen** [comment]
> @oopschen 那应该没问题了啊。你说的那些所谓依赖tiff:0/0的包在4.4.0被drop以后早就应该更新了依赖才对，不可能再出现还有包依赖写tiff:0/0的

如下所示：

[ebuild  N    ] media-libs/tiff-compat-4.4.0-r1 
[ebuild   R   ] app-office/wps-office-11.1.0.11698 [11.1.0.11698]
[blocks B     ] =media-libs/tiff-4.4* ("=media-libs/tiff-4.4*" is soft blocking media-libs/tiff-compat-4.4.0-r1)

 * Error: The above package list contains packages which cannot be
 * installed at the same time on the same system.

  (media-libs/tiff-4.4.0-r2:0/0::gentoo, installed) pulled in by
    >=media-libs/tiff-4.0.3-r6:=[abi_x86_32(-)?,abi_x86_64(-)?,abi_x86_x32(-)?,abi_mips_n32(-)?,abi_mips_n64(-)?,abi_mips_o32(-)?,abi_s390_32(-)?,abi_s390_64(-)?] (>=media-libs/tiff-4.0.3-r6:=[abi_x86_64(-)]) required by (media-libs/lcms-2.14-r4:2/2::gentoo, installed) USE="jpeg tiff zlib -doc -static-libs" ABI_X86="(64) -32 (-x32)"
    media-libs/tiff:0/0=[abi_x86_64(-)] required by (x11-libs/wxGTK-3.0.5.1-r1:3.0-gtk3/3.0-gtk3::gentoo, installed) USE="X libnotify opengl sdl tiff -debug -doc -gstreamer (-pch) -test -webkit" ABI_X86="(64) -32 (-x32)"
    >=media-libs/tiff-4.0.4:=[abi_x86_32(-)?,abi_x86_64(-)?,abi_x86_x32(-)?,abi_mips_n32(-)?,abi_mips_n64(-)?,abi_mips_o32(-)?,abi_s390_32(-)?,abi_s390_64(-)?] (>=media-libs/tiff-4.0.4:=[abi_x86_64(-)]) required by (media-libs/imlib2-1.9.1-r1:0/0::gentoo, installed) USE="X bzip2 gif jpeg mp3 png shm svg tiff webp zlib -apidoc -debug -eps -heif -jpeg2k -jpegxl -lzma -static-libs" ABI_X86="(64) -32 (-x32)" CPU_FLAGS_X86="sse2 (-mmx)"
    media-libs/tiff:0/0= required by (app-text/poppler-23.03.0:0/126::gentoo, installed) USE="cairo cxx introspection jpeg jpeg2k lcms png qt5 tiff utils -boost -cjk -curl -debug -doc -nss -verify-sig" ABI_X86="(64)"
    >=media-libs/tiff-3.5.7:0/0= required by (media-gfx/gimp-2.10.34-r1:0/2::gentoo, installed) USE="alsa gnome mng udev -aalib (-aqua) -debug -doc -heif -jpeg2k -jpegxl -openexr -postscript -test -unwind -vector-icons -webp -wmf -xpm" ABI_X86="(64)" CPU_FLAGS_X86="mmx sse"
    media-libs/tiff:= required by (gui-libs/gtk-4.10.3:4/4::gentoo, installed) USE="X cups introspection (-aqua) -broadway -cloudproviders -colord -examples (-ffmpeg) -gstreamer -sysprof -test (-vulkan) -wayland" ABI_X86="(64)" CPU_FLAGS_X86="f16c"
    media-libs/tiff:= required by (media-libs/libwebp-1.2.4-r1:0/7::gentoo, installed) USE="gif jpeg opengl png tiff -static-libs -swap-16bit-csp" ABI_X86="(64) -32 (-x32)" CPU_FLAGS_X86="sse2 sse4_1"
    media-libs/tiff required by (sci-libs/gdal-3.6.2:0/32::gentoo, installed) USE="curl gif jpeg pdf png python -armadillo (-doc) -fits -geos -gml -hdf5 -heif -java -jpeg2k -lzma -mysql -netcdf -odbc -ogdi -opencl -oracle -postgres -spatialite -sqlite -test -webp -xls -zstd" ABI_X86="(64)" CPU_FLAGS_X86="avx avx2 sse sse2 sse4_1 ssse3" PYTHON_SINGLE_TARGET="python3_11 -python3_10"
    >=media-libs/tiff-3.9.1:= required by (sci-libs/libgeotiff-1.7.1-r3:0/5::gentoo, installed) USE="jpeg tiff zlib -doc" ABI_X86="(64)"
    media-libs/tiff:0/0= required by (sci-libs/proj-9.1.1-r1:0/9::gentoo, installed) USE="tiff -curl -test" ABI_X86="(64)"
    media-libs/tiff:0/0= required by (media-gfx/imagemagick-7.1.1.6:0/7.1.1-43::gentoo, installed) USE="X bzip2 cxx jpeg lcms openmp pango png svg tiff truetype xml zlib -corefonts -djvu -fftw -fontconfig -fpx -graphviz -hdri -heif -jbig -jpeg2k -jpegxl -lqr -lzma -opencl -openexr -perl -postscript -q32 -q8 -raw -static-libs -test -webp -wmf -zip" ABI_X86="(64)"
    media-libs/tiff:0/0= required by (net-print/cups-filters-1.28.17:0/0::gentoo, installed) USE="dbus exif foomatic jpeg pdf png postscript tiff -ldap -pclm -perl -test -zeroconf" ABI_X86="(64)"
    media-libs/tiff:0/0= required by (media-libs/openjpeg-2.5.0-r4:2/7::gentoo, installed) USE="-doc -test" ABI_X86="(64) -32 (-x32)"
    >=media-libs/tiff-3.9.1:0/0= required by (sci-libs/libgeotiff-1.7.1-r3:0/5::gentoo, installed) USE="jpeg tiff zlib -doc" ABI_X86="(64)"
    media-libs/tiff:= required by (app-text/poppler-23.03.0:0/126::gentoo, installed) USE="cairo cxx introspection jpeg jpeg2k lcms png qt5 tiff utils -boost -cjk -curl -debug -doc -nss -verify-sig" ABI_X86="(64)"
    >=media-libs/tiff-3.5.7:= required by (media-gfx/gimp-2.10.34-r1:0/2::gentoo, installed) USE="alsa gnome mng udev -aalib (-aqua) -debug -doc -heif -jpeg2k -jpegxl -openexr -postscript -test -unwind -vector-icons -webp -wmf -xpm" ABI_X86="(64)" CPU_FLAGS_X86="mmx sse"
    >=media-libs/tiff-4:0/0= required by (media-libs/gegl-0.4.44:0.4/0.4::gentoo, installed) USE="cairo lcms openmp pdf sdl svg tiff -debug -ffmpeg -introspection -lensfun -openexr -raw -sdl2 -test -umfpack -v4l -vala -webp" ABI_X86="(64)"
    media-libs/tiff:0/0 required by (net-im/dingtalk-1.7.0.30419:0/0::local, installed) USE="" ABI_X86="(64)"
    media-libs/tiff:= required by (sci-libs/proj-9.1.1-r1:0/9::gentoo, installed) USE="tiff -curl -test" ABI_X86="(64)"
    >=media-libs/tiff-4:= required by (media-libs/gegl-0.4.44:0.4/0.4::gentoo, installed) USE="cairo lcms openmp pdf sdl svg tiff -debug -ffmpeg -introspection -lensfun -openexr -raw -sdl2 -test -umfpack -v4l -vala -webp" ABI_X86="(64)"
    media-libs/tiff:= required by (media-gfx/imagemagick-7.1.1.6:0/7.1.1-43::gentoo, installed) USE="X bzip2 cxx jpeg lcms openmp pango png svg tiff truetype xml zlib -corefonts -djvu -fftw -fontconfig -fpx -graphviz -hdri -heif -jbig -jpeg2k -jpegxl -lqr -lzma -opencl -openexr -perl -postscript -q32 -q8 -raw -static-libs -test -webp -wmf -zip" ABI_X86="(64)"
    >=media-libs/tiff-4.0.4:0/0=[abi_x86_64(-)] required by (media-libs/imlib2-1.9.1-r1:0/0::gentoo, installed) USE="X bzip2 gif jpeg mp3 png shm svg tiff webp zlib -apidoc -debug -eps -heif -jpeg2k -jpegxl -lzma -static-libs" ABI_X86="(64) -32 (-x32)" CPU_FLAGS_X86="sse2 (-mmx)"
    media-libs/tiff:= required by (net-print/cups-filters-1.28.17:0/0::gentoo, installed) USE="dbus exif foomatic jpeg pdf png postscript tiff -ldap -pclm -perl -test -zeroconf" ABI_X86="(64)"
    >=media-libs/tiff-4.0.3-r6:0/0=[abi_x86_64(-)] required by (media-libs/lcms-2.14-r4:2/2::gentoo, installed) USE="jpeg tiff zlib -doc -static-libs" ABI_X86="(64) -32 (-x32)"
    media-libs/tiff:= required by (media-libs/openjpeg-2.5.0-r4:2/7::gentoo, installed) USE="-doc -test" ABI_X86="(64) -32 (-x32)"
    >=media-libs/tiff-4.0.1:0/0= required by (app-text/ghostscript-gpl-10.01.1:0/10.01::gentoo, installed) USE="X cups dbus gtk (unicode) -static-libs" ABI_X86="(64)" L10N="-de (-ja) -ko -zh-CN -zh-TW"
    media-libs/tiff:0/0= required by (gui-libs/gtk-4.10.3:4/4::gentoo, installed) USE="X cups introspection (-aqua) -broadway -cloudproviders -colord -examples (-ffmpeg) -gstreamer -sysprof -test (-vulkan) -wayland" ABI_X86="(64)" CPU_FLAGS_X86="f16c"
    media-libs/tiff:0/0= required by (media-libs/libwebp-1.2.4-r1:0/7::gentoo, installed) USE="gif jpeg opengl png tiff -static-libs -swap-16bit-csp" ABI_X86="(64) -32 (-x32)" CPU_FLAGS_X86="sse2 sse4_1"
    >=media-libs/tiff-3.9.2:=[abi_x86_32(-)?,abi_x86_64(-)?,abi_x86_x32(-)?,abi_mips_n32(-)?,abi_mips_n64(-)?,abi_mips_o32(-)?,abi_s390_32(-)?,abi_s390_64(-)?] (>=media-libs/tiff-3.9.2:=[abi_x86_64(-)]) required by (x11-libs/gdk-pixbuf-2.42.10-r1:2/2::gentoo, installed) USE="introspection jpeg tiff -gtk-doc -test" ABI_X86="(64) -32 (-x32)"
    >=media-libs/tiff-4.0.1:= required by (app-text/ghostscript-gpl-10.01.1:0/10.01::gentoo, installed) USE="X cups dbus gtk (unicode) -static-libs" ABI_X86="(64)" L10N="-de (-ja) -ko -zh-CN -zh-TW"
    media-libs/tiff:=[abi_x86_32(-)?,abi_x86_64(-)?,abi_x86_x32(-)?,abi_mips_n32(-)?,abi_mips_n64(-)?,abi_mips_o32(-)?,abi_s390_32(-)?,abi_s390_64(-)?] (media-libs/tiff:=[abi_x86_64(-)]) required by (x11-libs/wxGTK-3.0.5.1-r1:3.0-gtk3/3.0-gtk3::gentoo, installed) USE="X libnotify opengl sdl tiff -debug -doc -gstreamer (-pch) -test -webkit" ABI_X86="(64) -32 (-x32)"
    >=media-libs/tiff-3.9.2:0/0=[abi_x86_64(-)] required by (x11-libs/gdk-pixbuf-2.42.10-r1:2/2::gentoo, installed) USE="introspection jpeg tiff -gtk-doc -test" ABI_X86="(64) -32 (-x32)"

  (media-libs/tiff-compat-4.4.0-r1:4/4::gentoo, ebuild scheduled for merge) pulled in by
    media-libs/tiff-compat:4 required by (app-office/wps-office-11.1.0.11698:0/0::gentoo-zh, ebuild scheduled for merge) USE="(-big-endian) -systemd" ABI_X86="(64)"

**Comment by Universebenzene** [comment]
@oopschen 你先把你这WPS卸掉然后把系统滚到最新再试试

**Comment by oopschen** [comment]
> @oopschen 你先把你这WPS卸掉然后把系统滚到最新再试试

无效哦，还是一样，倒不是这个包不存在或者太老，是其他包依赖了这个tiff包。
gentoo的官方仓库不知为什么存在两个同样的tiff包：tiff 和 tiff-compat

**Comment by Universebenzene** [comment]
@oopschen 存在的理由很简单，tiff-4.5.0以上库版本是 `libtiff.so.6` ，而很多二进制包还在依赖 `libtiff.so.5` ，tiff-compat就是为了提供这个.5版本的库的

至于你现在已经把portage tree同步到最新了还是有这问题应该是得想办法触发所有依赖tiff的包进行重编译。按说那些依赖tiff的包依赖不会是写死了 `tiff:0/0` 的，应该是像 `tiff:=` 这样，原则上是subslot变动触发重编译机制才对，现在他不触发是有点奇怪的。你再试试 `emerge -av1 tiff` 看看呢

**Comment by oopschen** [comment]
> @oopschen 存在的理由很简单，tiff-4.5.0以上库版本是 `libtiff.so.6` ，而很多二进制包还在依赖 `libtiff.so.5` ，tiff-compat就是为了提供这个.5版本的库的
> 
> 至于你现在已经把portage tree同步到最新了还是有这问题应该是得想办法触发所有依赖tiff的包进行重编译。按说那些依赖tiff的包依赖不会是写死了 `tiff:0/0` 的，应该是像 `tiff:=` 这样，原则上是subslot变动触发重编译机制才对，现在他不触发是有点奇怪的。你再试试 `emerge -av1 tiff` 看看呢

```

These are the packages that would be merged, in order:

Calculating dependencies  . ..... .... done!
Dependency resolution took 26.40 s.

[ebuild     U  ] media-libs/tiff-4.5.0:0/6::gentoo [4.4.0-r2:0/0::gentoo] USE="cxx jpeg zlib -jbig -lzma -static-libs -test -verify-sig -webp -zstd" ABI_X86="(64) -32 (-x32)" 2,267 KiB

Total: 1 package (1 upgrade), Size of downloads: 2,267 KiB

!!! Multiple package instances within a single package slot have been pulled
!!! into the dependency graph, resulting in a slot conflict:

media-libs/tiff:0

  (media-libs/tiff-4.5.0:0/6::gentoo, ebuild scheduled for merge) USE="cxx jpeg zlib -jbig -lzma -static-libs -test -verify-sig -webp -zstd" ABI_X86="(64) -32 (-x32)" pulled in by
    media-libs/tiff (Argument)

  (media-libs/tiff-4.4.0-r2:0/0::gentoo, installed) USE="cxx jpeg zlib -jbig -lzma -static-libs -test -verify-sig -webp -zstd" ABI_X86="(64) -32 (-x32)" pulled in by
    media-libs/tiff:0/0=[abi_x86_64(-)] required by (x11-libs/wxGTK-3.0.5.1-r1:3.0-gtk3/3.0-gtk3::gentoo, installed) USE="X libnotify opengl sdl tiff -debug -doc -gstreamer (-pch) -test -webkit" ABI_X86="(64) -32 (-x32)"
                   ^^^^^                                                                                                                                                                                                     
    >=media-libs/tiff-4.0.1:0/0= required by (app-text/ghostscript-gpl-10.01.1:0/10.01::gentoo, installed) USE="X cups dbus gtk (unicode) -static-libs" ABI_X86="(64)" L10N="-de (-ja) -ko -zh-CN -zh-TW"
                           ^^^^^                                                                                                                                                                          
    >=media-libs/tiff-4.0.3-r6:0/0=[abi_x86_64(-)] required by (media-libs/lcms-2.14-r4:2/2::gentoo, installed) USE="jpeg tiff zlib -doc -static-libs" ABI_X86="(64) -32 (-x32)"
                              ^^^^^                                                                                                                                              
    >=media-libs/tiff-3.9.2:0/0=[abi_x86_64(-)] required by (x11-libs/gdk-pixbuf-2.42.10-r1:2/2::gentoo, installed) USE="introspection jpeg tiff -gtk-doc -test" ABI_X86="(64) -32 (-x32)"
                           ^^^^^                                                                                                                                                           
    media-libs/tiff:0/0= required by (media-libs/openjpeg-2.5.0-r4:2/7::gentoo, installed) USE="-doc -test" ABI_X86="(64) -32 (-x32)"
                   ^^^^^                                                                                                              
    >=media-libs/tiff-4.0.4:0/0=[abi_x86_64(-)] required by (media-libs/imlib2-1.9.1-r1:0/0::gentoo, installed) USE="X bzip2 gif jpeg mp3 png shm svg tiff webp zlib -apidoc -debug -eps -heif -jpeg2k -jpegxl -lzma -static-libs" ABI_X86="(64) -32 (-x32)" CPU_FLAGS_X86="sse2 (-mmx)"
                           ^^^^^                                                                                                                                                                                                                                                         
    >=media-libs/tiff-3.5.7:0/0= required by (media-gfx/gimp-2.10.34-r1:0/2::gentoo, installed) USE="alsa gnome mng udev -aalib (-aqua) -debug -doc -heif -jpeg2k -jpegxl -openexr -postscript -test -unwind -vector-icons -webp -wmf -xpm" ABI_X86="(64)" CPU_FLAGS_X86="mmx sse"
                           ^^^^^                                                                                                                                                                                                                                                   
    media-libs/tiff:0/0= required by (gui-libs/gtk-4.10.3:4/4::gentoo, installed) USE="X cups introspection (-aqua) -broadway -cloudproviders -colord -examples (-ffmpeg) -gstreamer -sysprof -test (-vulkan) -wayland" ABI_X86="(64)" CPU_FLAGS_X86="f16c"
                   ^^^^^                                                                                                                                                                                                                                    
    >=media-libs/tiff-4:0/0= required by (media-libs/gegl-0.4.44:0.4/0.4::gentoo, installed) USE="cairo lcms openmp pdf sdl svg tiff -debug -ffmpeg -introspection -lensfun -openexr -raw -sdl2 -test -umfpack -v4l -vala -webp" ABI_X86="(64)"
                       ^^^^^                                                                                                                                                                                                                    
    media-libs/tiff:0/0= required by (media-gfx/imagemagick-7.1.1.6:0/7.1.1-43::gentoo, installed) USE="X bzip2 cxx jpeg lcms openmp pango png svg tiff truetype xml zlib -corefonts -djvu -fftw -fontconfig -fpx -graphviz -hdri -heif -jbig -jpeg2k -jpegxl -lqr -lzma -opencl -openexr -perl -postscript -q32 -q8 -raw -static-libs -test -webp -wmf -zip" ABI_X86="(64)"
                   ^^^^^                                                                                                                                                                                                                                                                                                                                                     
    media-libs/tiff:0/0= required by (app-text/poppler-23.03.0:0/126::gentoo, installed) USE="cairo cxx introspection jpeg jpeg2k lcms png qt5 tiff utils -boost -cjk -curl -debug -doc -nss -verify-sig" ABI_X86="(64)"
                   ^^^^^                                                                                                                                                                                                 
    media-libs/tiff:0/0= required by (net-print/cups-filters-1.28.17:0/0::gentoo, installed) USE="dbus exif foomatic jpeg pdf png postscript tiff -ldap -pclm -perl -test -zeroconf" ABI_X86="(64)"
                   ^^^^^                                                                                                                                                                            
    media-libs/tiff:0/0= required by (sci-libs/proj-9.1.1-r1:0/9::gentoo, installed) USE="tiff -curl -test" ABI_X86="(64)"
                   ^^^^^                                                                                                   
    media-libs/tiff:0/0 required by (net-im/dingtalk-1.7.0.30419:0/0::local, installed) USE="" ABI_X86="(64)"
                   ^^^^                                                                                       
    >=media-libs/tiff-3.9.1:0/0= required by (sci-libs/libgeotiff-1.7.1-r3:0/5::gentoo, installed) USE="jpeg tiff zlib -doc" ABI_X86="(64)"
                           ^^^^^                                                                                                            
    media-libs/tiff:0/0= required by (media-libs/libwebp-1.2.4-r1:0/7::gentoo, installed) USE="gif jpeg opengl png tiff -static-libs -swap-16bit-csp" ABI_X86="(64) -32 (-x32)" CPU_FLAGS_X86="sse2 sse4_1"
                   ^^^^^                                                                                                                                                                                    


It may be possible to solve this problem by using package.mask to
prevent one of those packages from being selected. However, it is also
possible that conflicting dependencies exist such that they are
impossible to satisfy simultaneously.  If such a conflict exists in
the dependencies of two different packages, then those packages can
not be installed simultaneously.

For more information, see MASKED PACKAGES section in the emerge man
page or refer to the Gentoo Handbook.


```

**Comment by Universebenzene** [comment]
> `media-libs/tiff:0/0 required by (net-im/dingtalk-1.7.0.30419:0/0::local, installed) USE="" ABI_X86="(64)"`

@oopschen 这包是不是你自己打的？你自己ebuild里依赖是咋写的？

**Comment by oopschen** [comment]
> @oopschen 你先把你这WPS卸掉然后把系统滚到最新再试试

官方如此：
https://github.com/microcai/gentoo-zh/blob/master/net-im/dingtalk/dingtalk-1.4.0.20909-r1.ebuild

**Comment by Universebenzene** [comment]
@oopschen 

[人家这个](https://github.com/microcai/gentoo-zh/blob/13bc1a11fc1572a3e226a2fafca28ebf86752665/net-im/dingtalk/dingtalk-1.4.0.20909-r1.ebuild#L25)是tiff:0/0和tiff-compat二选一，你确定你写的是二选一嘛

**Comment by oopschen** [comment]
> @oopschen
> 
> [人家这个](https://github.com/microcai/gentoo-zh/blob/13bc1a11fc1572a3e226a2fafca28ebf86752665/net-im/dingtalk/dingtalk-1.4.0.20909-r1.ebuild#L25)是tiff:0/0和tiff-compat二选一，你确定你写的是二选一嘛

```
 RDEPEND="
     dev-libs/libthai
     dev-qt/qtgui
     || ( media-libs/tiff:0/0 media-libs/tiff-compat:4 )
     media-sound/pulseaudio
     media-video/rtmpdump
     net-misc/curl
     net-nds/openldap
     sys-libs/zlib
     sys-process/procps
     x11-libs/gtk+:2
     x11-libs/gtk+:3
     x11-libs/libXScrnSaver
     >=x11-libs/cairo-1.17.4
```
是的

**Comment by Universebenzene** [comment]
@oopschen 要不你先临时把这个dingtalk卸掉再-av1 tiff试试看还有没有问题

**Comment by oopschen** [comment]
根据官方文档已解决相关问题。https://wiki.gentoo.org/wiki/User:Kentnl/Tips/Fixing_slot_conflicts
@Universebenzene  多谢
