### ISSUE TITLE
mirror://pypi/ 链接失效，建议更新为https://pypi.io的形式

### ISSUE THREAD

**Issue by LuckyXixi** [Gentoo-zh/gentoo-zh#3352]
dev-python中的ebuild SRC_URI链接失效

问题参考：https://bugs.gentoo.org/580648

建议更换为SRC_URI="https://pypi.io/packages/source/${PN::1}/${PN}/${P}.tar.gz"

**Comment by peeweep** [comment]
对于 pypi 的 distfiles ，最新的写法不再是写 SRC_URI，而是使用 metadata.xml 和 inherit pypi 代替

**Comment by Universebenzene** [comment]
> 建议更换为SRC_URI="[https://pypi.io/packages/source/${PN::1}/${PN}/${P}.tar.gz](https://pypi.io/packages/source/$%7BPN::1%7D/$%7BPN%7D/$%7BP%7D.tar.gz)"

并不。官方的建议是直接改用 `pypi.eclass` 。楼上peep菊苣也说了。楼主引用的这个bug都是16年的实在是过时了。pypi.eclass是今年初刚引入的新eclass，自然不能再看16年的上古老bug

**Comment by LuckyXixi** [comment]
好吧，我是看到gentoo repo 里面的包有这么用的。我在安装feeluown时遇到janus找不到mirror的报错。这么改过后问题解决了。目前gentoo-zh dev-python里的ebuild貌似没有inherit pypi。

**Comment by Universebenzene** [comment]
> 好吧，我是看到gentoo repo 里面的包有这么用的。我在安装feeluown时遇到janus找不到mirror的报错。这么改过后问题解决了。目前gentoo-zh dev-python里的ebuild貌似没有inherit pypi。

其实今年上半年main tree的py包凡是用pypi source的都在陆续切到pypi.eclass，楼主是没找对范例。

gentoo-zh 这的临时的解决方法是把thirdpartymirror先加回来然后日后慢慢把用到pypi mirror 的ebuild一个个都改过去。看菊苣们怎么决定了

**Comment by peeweep** [comment]
都迁到 pypi.eclass 吧，现在写了 mirror 的包也不算多

**Comment by peeweep** [comment]
已经更新 https://github.com/microcai/gentoo-zh/pull/3356

**Comment by liangyongxiang** [comment]
如果还有问题可以重新打开issue
