### ISSUE TITLE
Can anyone write a build file for this awesome PDF app?

### ISSUE THREAD

**Issue by Nirodhiko** [Gentoo-zh/gentoo-zh#3405]
Gentoo is the only distribution that this awesome app is not supported compiled on. [sioyek](https://github.com/ahrm/sioyek)

**Comment by st0nie** [comment]
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=sioyek
Gentoo is not the only distribution that doesn't package this software, and I don't think it would be hard to write an ebuild modeled after AUR's PKGBUILD, so you can try it yourself first.
PR welcome.
If you submit your own ebuild, we'll be happy to go help you improve it.

**Comment by Nirodhiko** [comment]
> https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=sioyek Gentoo is not the only distribution that doesn't package this software, and I don't think it would be hard to write an ebuild modeled after AUR's PKGBUILD, so you can try it yourself first. PR welcome. If you submit your own ebuild, we'll be happy to go help you improve it.

Haha~
If I can write ebuild, I will write it by myself. 
Just a suggestion~
