### ISSUE TITLE
[nvchecker] app-misc/rmtrash can be bump to 1.15

### ISSUE THREAD

**Issue by microcai** [Gentoo-zh/gentoo-zh#3595]
oldver: 1.14
CC: @CHN-beta

**Comment by CHN-beta** [comment]
我已经不用gentoo了，是否应该将这个包drop掉？

**Comment by liangyongxiang** [comment]
> 我已经不用gentoo了，是否应该将这个包drop掉？

建议是先去掉 nvcheker 的提醒。pr 之后我可以直接合并。

如果要drop的话发个 issue 看看有没有人愿意接手。
