### ISSUE TITLE
net-proxy/daed-0.3.3_p1: does not handle ${CFLAGS} properly

### ISSUE THREAD

**Issue by liuyujielol** [Gentoo-zh/gentoo-zh#3720]
在我这边构建失败:
```
vite v4.4.9 building for production...
clang: error: unsupported option '-march=' for target 'bpfel'
clang: warning: argument unused during compilation: '-mtune=znver2' [-Wunused-command-line-argument]
Error: can't execute clang: exit status 1
```
build.log: https://gist.github.com/liuyujielol/a1f8f9fc591de21e493e3b56e5be52f0

**Comment by liuyujielol** [comment]
make.conf: https://gist.github.com/liuyujielol/9b7e669efe7be4c0643e252fd31344b7
emerge --info '=net-proxy/daed-0.3.3_p1::gentoo-zh' :  https://gist.github.com/liuyujielol/3a795551e6f5d876a22664533ca2eb8f

**Comment by liangyongxiang** [comment]
@liuyujielol @st0on 看起来直接将cflag传递过去会有问题

**Comment by liuyujielol** [comment]
我仔细研究了一下，报错的部分应该是:
```
cd dae-core && \
make ebpf && \
cd ../ && \
touch dae-core/control/bpf_bpfeb.o
make[2]: Entering directory '/tmp/portage/net-proxy/daed-0.3.3_p1/work/wing/dae-core'
-strip=/usr/lib/llvm/17/bin/llvm-strip
```

submodule `wing`的submdule `dae`引入clang编译bpfel,bpfeb这两个llvm-targets:
https://github.com/daeuniverse/dae/blob/3b8d248827c4d96ad8fef2c20e5cbbcf3e0213c1/Makefile

然后我重新编译了一下dae,得到了同样的错误:
```
make -j16 VERSION=0.3.0 GOFLAGS=-buildvcs=false CC=clang 'CFLAGS=-march=znver2 -mtune=znver2 -O2 -pipe -fno-stack-protector' 
-strip=/usr/lib/llvm/17/bin/llvm-strip
clang: error: unsupported option '-march=' for target 'bpfel'
clang: warning: argument unused during compilation: '-mtune=znver2' [-Wunused-command-line-argument]
Error: can't execute clang: exit status 1
exit status 1
control/control.go:8: running "go": exit status 1
make: *** [Makefile:83: ebpf] Error 1
```


现在看来问题应该是dae编译ebpf的时候产生了`clang: error: unsupported option '-march=' for target 'bpfel'`
CFLAGS里面去掉`-march=` 和 `-mtune=`应该就行了
不知道是不是因为clang又改了什么

**Comment by seven-mile** [comment]
看起来 `filter-flags "-march=*" "-mtune=*"` 还不够。

我之前一直用 `-march=native` 。今天升级 `profile` 的时候 `sys-devel/gcc` 由于 cache_size 不一致的问题让我用 `app-misc/resolve-march-native` 输出的 safe cflags，我在 13700K 上得到的结果是
```
COMMON_FLAGS="-march=alderlake -mabm -mno-cldemote -mno-kl -mno-sgx -mno-widekl -mshstk --param=l1-cache-line-size=64 --param=l1-cache-size=32 --param=l2-cache-size=30720 -O2 -pipe"
```

然后切换 CFLAGS 之后，编译 `net-proxy/dae` 的时候就出现了以下问题
```sh
>>> Compiling source in /var/tmp/portage/net-proxy/dae-0.6.0_rc1/work ...
make -j18 -l18 VERSION=0.6.0_rc1 'GOFLAGS=-buildvcs=false -w' 
-strip=/usr/lib/llvm/17/bin/llvm-strip
clang: error: unknown argument '-mabm'; did you mean '-marm'?
Error: can't execute clang: exit status 1
exit status 1
control/control.go:8: running "go": exit status 1
```

关键应该是新引入的这个 `-mabm` 选项不受 clang 支持（gcc 是支持的），通过 `package.env` 重置 CFLAGS 后问题解决。

我想这和这个 issue 应该是相同问题，虽然它并不是直接和 target bpfel 相关，但它是由于 dae 需要编译到 bpfel，从而默认选用了 clang 编译，而某些 CFLAGS 不受 clang 支持导致的。

直接分析的话，原因是 `filter-flags "-march=*" "-mtune=*"` 这个修复还不够强？

但本质上，应该讲这个包其实承担了一个**交叉编译**的任务，其 CFLAGS 的处理 Gentoo 应该有相关的最佳实践，不知道会不会有参考价值。

**Comment by liuyujielol** [comment]
flag-o-matic.eclass的strip-unsupported-flags()应该可以解决问题
