### ISSUE TITLE
[nvchecker] sys-kernel/xanmod-hybrid can be bump to 6.6.1

### ISSUE THREAD

**Issue by microcai** [Gentoo-zh/gentoo-zh#3858]

**Comment by liuyujielol** [comment]
直接手动把标题改了，issue bumper是不是就会用这个issue了

**Comment by liangyongxiang** [comment]
我记得改了就不会再使用这个了。

已经改好了：https://github.com/microcai/gentoo-zh/commit/078d4ba00d906bf91e55eb978f33374dcba16226
