### ISSUE TITLE
x11-misc/ly:不会安装init脚本

### ISSUE THREAD

**Issue by Nuralii1i** [Gentoo-zh/gentoo-zh#4066]
安装完ly之后发现`sudo systemctl enable ly`提示`Failed to enable unit: Unit file ly.service does not exist.`
瞎研究一顿ebuild,没发现有安装上游提供的init脚本的逻辑，在天本菊苣的建议下选择了提issue
望修复
感谢

**Comment by liangyongxiang** [comment]
@OriPoin

**Comment by Nuralii1i** [comment]
#4069 已修
