### ISSUE TITLE
建议为以下包添加 ~loong 的 keyword 以便于在 LoongArch 上安装和使用

### ISSUE THREAD

**Issue by HougeLangley** [Gentoo-zh/gentoo-zh#4277]
![Screenshot_20240222_233954](https://github.com/microcai/gentoo-zh/assets/1161594/4937f5d9-fcf7-4a17-bcaf-31e4f72ff04f)

包括以上包

**Comment by liangyongxiang** [comment]
你来keyword？

**Comment by biergaizi** [comment]
如果软件包是 Gentoo 官方的，而且你已经测试过确定没问题，应该直接向 Gentoo 官方提出，就不用走（也不应该走）二手 gentoo-zh 了。先在 bugs.gentoo.org 报 Issue 提出缺少 keyword，然后向 https://github.com/gentoo/gentoo 源提交 Pull Request，并链接 bug 的编号。

**Comment by Universebenzene** [comment]
@biergaizi 不过这些包好像没有一个是Gentoo官方的呃

**Comment by biergaizi** [comment]
@Universebenzene 我印象中 v2ray 是官方的。看了看，并不是。抱歉，记错了。
