### ISSUE TITLE
www-client/brave should be a source-based package

### ISSUE THREAD

**Issue by blackteahamburger** [Gentoo-zh/gentoo-zh#4315]
According to the usual naming rules, www-client/brave should be a source-based package. We can rename the original www-client/brave to www-client/brave-bin and add a source-based www-client/brave.

**Comment by irort** [comment]
> According to the usual naming rules, www-client/brave should be a source-based package. We can rename the original www-client/brave to www-client/brave-bin and add a source-based www-client/brave.

OK, I will rename this package. But I checked the brave-browser wiki, it use npm build the package, and it will probably be as large project as building www-client/chromium. I can't pack source-based www-client/brave.

**Comment by blackteahamburger** [comment]
> I can't pack source-based www-client/brave.

Can you talk about why you couldn't pack it? It indeed costs a lot to build, but that's no reason not to pack it.

**Comment by biergaizi** [comment]
> Can you talk about why you couldn't pack it? 

The complexity is too high. I won't be surprised if it takes ~100 hours of work to package that properly.

If it's as large as Chromium, it likely includes around 100 bundled dependencies. For example, Chromium even builds its own version of the LLVM/clang toolchain. By Gentoo's standard, dependencies must be packaged separately, which means one has to analyze each dependency separately and change the build system to use the system version, which is an extremely time-consuming process. For Chromium, some exceptions can be made. But the resulted ebuild is still more than 1000 lines. Further, if "it uses npm to build the package", it also suggests that it uses its own non-standard build system, which would be highly difficult to work with.
