### ISSUE TITLE
net-im/weixin

### ISSUE THREAD

**Issue by vastchen** [Gentoo-zh/gentoo-zh#4491]
微信可以设置最新的linux微信版本么？虽然未正式发行但是看到archlinux  ubuntu有了wechat-universal-bwrap,在github上亦有
https://github.com/7Ji-PKGBUILDs/wechat-universal-bwrap/

**Comment by liangyongxiang** [comment]
https://github.com/microcai/gentoo-zh/pull/4489

**Comment by Universebenzene** [comment]
#4489 刚刚才把包完善完毕，楼主咋没先搜一搜

**Comment by liangyongxiang** [comment]
刚刚已经合并，我本地测试可以用。但是没找到HIDPI选项，高分屏可能有些问题。

**Comment by vastchen** [comment]
谢谢，刚看到。
