### ISSUE TITLE
QQ fcitx输入异常问题

### ISSUE THREAD

**Issue by haowuge** [Gentoo-zh/gentoo-zh#4496]
hello all
我尝试升级QQ版本，但测试中发现FCITX输入异常，这种情况我该如何排查？谢谢

修改的ebuild如下：https://github.com/haowuge/gentoo-zh/commit/7d7034e1e76e6dcd30075d416796b80c290cc2c6

(可以看到输入框并没有回车，但是字符上屏了，我测试过wechat-universal-bwrap不存在这种现象，
konsole，firefox等原生应用也不存在这种情况)
![fcitx](https://haowuge.github.io/pull_requests_images/2024-04-08/qq_fcitx.gif)

**Comment by st0nie** [comment]
If using X11 or Xwayland
Consider setting `GTK_IM_MODULE=fcitx`
and make sure `app-i18n/fcitx-gtk[gtk3]` installed

If using wayland
add `--enable-wayland-ime` to `~/.config/qq-electron-flags.conf`

**Comment by haowuge** [comment]
> If using X11 or Xwayland Consider setting `GTK_IM_MODULE=fcitx` and make sure `app-i18n/fcitx-gtk[gtk3]` installed
> 
> If using wayland add `--enable-wayland-ime` to `~/.config/qq-electron-flags.conf`

并没有什么效果，依旧会部分上屏
❯ cat ~/.config/qq-electron-flags.conf
--enable-wayland-ime
╭─░▒▓     /var/db/repos/gentoo-zh/net-im/tencent-qq     master ▓▒░            ░▒▓ ✔  18:48:19   ▓▒░─╮
╰─

**Comment by st0nie** [comment]
在下一行加
`--ozone-platform-hint=auto`

**Comment by haowuge** [comment]
> 在下一行加 `--ozone-platform-hint=auto`

您回太快了，我刚想了下，发现app-i18n/fcitx-gtk没安装，安好了之后就正常了，
qq-electron-flags.conf （也删掉了）一切正常，谢谢您
