### ISSUE TITLE
net-im/tencent-qq bwrap `~/.config/dconf` to make gsettings styling work

### ISSUE THREAD

**Issue by seven-mile** [Gentoo-zh/gentoo-zh#4504]
In the net-im/tencent-qq package, the ~/.config/dconf directory is not correctly mapped by bwrap in start.sh. As a result, user-defined themes configured via gsettings are not applied as expected.

Observable Issues:

* Cursor theme and size revert to Adwaita/24 on all QQ windows.
* File pickers appear in the Adwaita theme.

[Reference AUR comment](https://aur.archlinux.org/packages/linuxqq-nt-bwrap#comment-962302)

I don't know whether other bwrap packages are facing similar problems, which could be open for discussion.

The fix should be like

```diff
--- gentoo-zh/net-im/tencent-qq/files/start.sh	2024-01-06 16:51:00.299369685 +0800
+++ local/net-im/tencent-qq/files/start.sh	2024-04-10 19:06:21.912161246 +0800
@@ -120,6 +120,7 @@
     --ro-bind-try "${FONTCONFIG_HOME}" "${FONTCONFIG_HOME}" \
     --ro-bind-try "${HOME}/.icons" "${HOME}/.icons" \
     --ro-bind-try "${HOME}/.local/share/.icons" "${HOME}/.local/share/.icons" \
+    --ro-bind-try "${HOME}/.config/dconf" "${HOME}/.config/dconf" \
     --ro-bind-try "${XDG_CONFIG_HOME}/gtk-3.0" "${XDG_CONFIG_HOME}/gtk-3.0" \
     --ro-bind /etc/nsswitch.conf /etc/nsswitch.conf \
     --ro-bind-try /run/systemd/userdb/ /run/systemd/userdb/ \
```

**Comment by liangyongxiang** [comment]
@xen0n

**Comment by st0nie** [comment]
@seven-mile pr welcome

**Comment by st0nie** [comment]
```shell
ln -s /usr/share/icons/breeze_cursors ~/.icons/default
```
Maybe this helps

**Comment by seven-mile** [comment]
`GTK_USE_PORTAL=1` should be enough.
