### ISSUE TITLE
net-im/tencent-qq-3.2.7_p23159: KDE（Wayland）下不能截图

### ISSUE THREAD

**Issue by haowuge** [Gentoo-zh/gentoo-zh#4655]
net-im/tencent-qq-3.2.7_p23159: KDE（Wayland）下不能截图，点击截图按钮没任何反应
GNOME(Wayland下可以正常截图)

**Comment by liangyongxiang** [comment]
这个版本已经drop, 如果新版还有这个问题可以重新编辑issue然后再打开
