### ISSUE TITLE
net-misc/rustdesk: Request for Update

### ISSUE THREAD

**Issue by cppcloud** [Gentoo-zh/gentoo-zh#4848]
Hello Maintainers,

I am writing to request an update for the net-misc/rustdesk package in the gentoo_zh repository. The current version in the repository is 1.23, which is now behind the latest stable release 1.2.6 available from the official RustDesk sources.

Details:

Current package version in gentoo_zh: 1.2.3
Latest available version: 1.2.6
Source of the latest version: [RustDesk Release 1.2.6](https://github.com/rustdesk/rustdesk/releases/tag/1.2.6)

It would be beneficial for users to have access to the newest version, as it includes significant improvements and features that enhance the functionality and security of RustDesk.

Additional Context:
Updating to the latest version will ensure users have the most stable and secure experience using RustDesk, addressing critical bug fixes and performance enhancements.

Thank you for considering this update. Your efforts in maintaining the gentoo_zh repository are greatly appreciated.

Best regards

**Comment by Linerre** [comment]
The current verion, `1.23`, may be a typo, which should be, as you pointed out, `1.2.3`.  The original maintainer thus may  have not been notified about this for quite a while.  

Would you consider contacting the maintainer directly or creating a PR to fix this yourself?
