### ISSUE TITLE
app-editors/zed: Chinese display error

### ISSUE THREAD

**Issue by liangyongxiang** [Gentoo-zh/gentoo-zh#4955]
[test-a.md](https://github.com/user-attachments/files/16324628/test-a.md)

![image](https://github.com/user-attachments/assets/4c268d70-cd76-4a73-ac1e-81133d7b8a68)

@liuyujielol

**Comment by liuyujielol** [comment]
ui_font_familiy和buffer_font_family设置的什么？
我这边不设置和设置IBMPlexSans效果都是正常的
![image](https://github.com/user-attachments/assets/fa86a4d8-15d0-487b-8585-2866b91b5c2f)

**Comment by liangyongxiang** [comment]
[settings.json](https://github.com/user-attachments/files/16325170/settings.json)

我都没有设置。这是我的settings.json

**Comment by liuyujielol** [comment]
我试了试Source Code Pro和DejaVuSansMono都没有问题
我能想到的问题可能是fontconfig没有配置中文字体解析
[53-cjk.conf](https://github.com/user-attachments/files/16325173/53-cjk.conf.txt)

**Comment by liuyujielol** [comment]
> [settings.json](https://github.com/user-attachments/files/16325170/settings.json)
> 
> 我都没有设置。这是我的settings.json

"buffer_font_family":  ,不能冒号后面什么都没有，json解析错误
但是这好像只会导致markdown文件[中文]出问题...

**Comment by liangyongxiang** [comment]
> > [settings.json](https://github.com/user-attachments/files/16325170/settings.json)
> > 我都没有设置。这是我的settings.json
> 
> "buffer_font_family": ,不能冒号后面什么都没有，json解析错误 但是这好像只会导致markdown文件[中文]出问题...

抱歉，这是刚刚编辑的时候没清理干净留下来的。
我现在直接删除~/.config/zed目录，然后杀掉所有zed-editor进程，重新运行。出现的问题也是最上面那样的。

**Comment by liuyujielol** [comment]
设置成这样"buffer_font_family": ""也是正常的
![image](https://github.com/user-attachments/assets/00104eec-d9cb-4a49-8d03-489d5d69f325)
设置成"buffer_font_family": ,会json解析错误,这之后的全部设置都会失效，比如主题就没了
![image](https://github.com/user-attachments/assets/36b6bd0a-605f-44a7-8658-a295ea187816)

**Comment by liuyujielol** [comment]
> > > [settings.json](https://github.com/user-attachments/files/16325170/settings.json)
> > > 我都没有设置。这是我的settings.json
> > 
> > 
> > "buffer_font_family": ,不能冒号后面什么都没有，json解析错误 但是这好像只会导致markdown文件[中文]出问题...
> 
> 抱歉，这是刚刚编辑的时候没清理干净留下来的。 我现在直接删除~/.config/zed目录，然后杀掉所有zed-editor进程，重新运行。出现的问题也是最上面那样的。

我不管设置不设置font_family都没有这个问题
删除~/.config/zed重新打开设置编辑保存一下试试？或者同时删除~/.local/share/zed/db和~/.config/zed

**Comment by liangyongxiang** [comment]
> 设置成这样"buffer_font_family": ""也是正常的

测试了的确是这样。

1. 删除 ~/.config/zed 目录后打开test-a.md，没法显示。
2. 点击welcome配置，它生成的~/.config.zed/settings 也是没法显示。
3. 手动添加你说的 "buffer_font_family": "" 后正常

**Comment by liuyujielol** [comment]
> 
> 测试了的确是这样。
> 
> 1. 删除 ~/.config/zed 目录后打开test-a.md，没法显示。
> 2. 点击welcome配置，它生成的~/.config.zed/settings 也是没法显示。
> 3. 手动添加你说的 "buffer_font_family": "" 后正常

可能是~/.local/share/zed/db保存的设置没有更新

**Comment by liangyongxiang** [comment]
> ~/.local/share/zed

应该不是没有更新。

1.  我使用zed打开settings.json加上"buffer_font_family": ""，关闭zed，重新打开test-aaaa.md，可以显示。
2. 我使用zed打开settings.json去掉或注释掉加上"buffer_font_family": ""，关闭zed，重新打开test-aaaa.md，不可以显示。
3. 重复测试可以复现

**Comment by liangyongxiang** [comment]
可以看到 屏蔽了这行和加上这行，英文字体是不一样的：
![image](https://github.com/user-attachments/assets/3103db11-f3e9-4eb7-8dd1-fd308f8a3c86)
![image](https://github.com/user-attachments/assets/a7eb2607-1374-4afc-9791-5739c9d673b8)

**Comment by liuyujielol** [comment]
看来确实是有bug
![image](https://github.com/user-attachments/assets/1a4e93c5-5fbf-4706-a717-a64005aea511)

我之前不设置*_font_family也可以显示，可能是主题有字体设置

![image](https://github.com/user-attachments/assets/30e1a75d-79d5-43da-a718-063afdfe155a)

**Comment by liangyongxiang** [comment]
> 看来确实是有bug ![image](https://private-user-images.githubusercontent.com/19249377/350781922-1a4e93c5-5fbf-4706-a717-a64005aea511.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE1NzkxNTIsIm5iZiI6MTcyMTU3ODg1MiwicGF0aCI6Ii8xOTI0OTM3Ny8zNTA3ODE5MjItMWE0ZTkzYzUtNWZiZi00NzA2LWE3MTctYTY0MDA1YWVhNTExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIxVDE2MjA1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWExYjAyZDYzNmZiZTFmNjY5NDYwMThjMzIyYjc3NmY0Nzg3OGJmYzQzYTVjZTdjNWMwNjU3YTIzNjI3YmE2NDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6RnLdaRrEfiDSwJYXt5IwjGD97-tOYt1DqtMRbSaNj0)
> 
> 我之前不设置*_font_family也可以显示，可能是主题有字体设置

你能复现就最好了。成功把锅分给你了。我的配置文件：
[settings.json](https://github.com/user-attachments/files/16325275/settings.json)

**Comment by liuyujielol** [comment]
🤣

**Comment by liuyujielol** [comment]
看起来之前把默认字体从ZedMono切换到IBMPlexMono就是为了这个问题。。。
https://github.com/zed-industries/zed/issues/9310
https://github.com/zed-industries/zed/pull/13568
https://github.com/zed-industries/zed/pull/13596
应该不是打包的问题，我简单测试了一下，好像只有markdown有这个问题，
估计是markdown插件没有写好不设置buffer_font_family的情况

**Comment by liangyongxiang** [comment]
今天测试还是有类似的问题。

**Comment by liangyongxiang** [comment]
还是有类似的问题

**Comment by liuyujielol** [comment]
问题可能出在默认主题One Light上面，One Dark是没有问题的
在不设置主题，主题加载出错的情况下，默认主题就是One Light
在不设置buffer_font_family的情况下，italic中文字体是没法正常加载的
![image](https://github.com/user-attachments/assets/11ef4d3f-e248-4b37-94bd-fdcc753c77ef)

![image](https://github.com/user-attachments/assets/675f06a8-cf7e-4c9a-9b9a-51af4254d81d)
![image](https://github.com/user-attachments/assets/9b64b05b-ebff-4cad-8ad2-fa81b9f11026)
