### ISSUE TITLE
app-editors/zed：报错找不到xdg-desktop-portal实现

### ISSUE THREAD

**Issue by Nuralii1i** [Gentoo-zh/gentoo-zh#4989]
桌面环境：DWM
Profile: `default/linux/amd64/23.0/desktop/systemd (stable)`
app-editors/zed在用`Ctrl o` 快捷键时右下角会弹出 Couldn't open file picker due to missing xdg-desktop-portal implementation
我尝试手动安装,尝试了xdg-desktop-portal-gtk/xapp/gnome，依旧提示这个

**Comment by liuyujielol** [comment]
具体报错的那几行log发一下，
然后发一下`eix -I desktop-portal --only-names                               `                                                    
我是这样的

```
eix -I desktop-portal --only-names                                                                                   
kde-plasma/xdg-desktop-portal-kde
sys-apps/xdg-desktop-portal
sys-apps/xdg-desktop-portal-gtk

```

**Comment by liuyujielol** [comment]
DWM的话确保自己在启动桌面的时候有正常启动xdg-desktop-portal
比如看看`loginctl session-status`输出里面有没有关于portal的日志
或者直接用DBus读
`busctl --user call org.freedesktop.portal.Desktop /org/freedesktop/portal/desktop org.freedesktop.portal.Settings Read ss "org.freedesktop.appearance" "color-scheme"`
```
org.freedesktop.appearance color-scheme u
Indicates the system's preferred color scheme. Supported values are:

0: No preference
1: Prefer dark appearance
2: Prefer light appearance
Unknown values should be treated as 0 (no preference).
```
我这边KDE6+Wayland的输出是v v u 2

**Comment by Nuralii1i** [comment]
感谢回复，应该只装一个xdg-desktop-portal实现，看到大佬回复后重启了一下，然后发现`busctl --user call org.freedesktop.portal.Desktop /org/freedesktop/portal/desktop org.freedesktop.portal.Settings Read ss "org.freedesktop.appearance" "color-scheme"`超时，我卸掉了其他俩。留下`xdg-desktop-portal-gtk`，输出有结果了输出`v v u 0`，zed也可以正常打开选择窗口了

**Comment by liuyujielol** [comment]
> 应该只装一个xdg-desktop-portal实现

安装多个不同的xdg-desktop-portal实现是没有问题的。
你的问题感觉更像是没有配置对，参考ArchWiki，xdg-desktop-portal-xapp是没有实现FileChooser的
在`/usr/share/xdg-desktop-portal/*.conf`或者`$XDG_CONFIG_HOME/xdg-desktop-portal/*.conf`里面指定一个可以用的实现+有一个可以被正常调用的文件管理器应该就正常了
- https://wiki.archlinuxcn.org/wiki/XDG桌面门户

题外话，xdg-desktop-portal实现一大堆，支持的环境各不相同、对接口的实现有的完善有的不完善，也不太适合写到ebuild的依赖里面

**Comment by Nuralii1i** [comment]
> > 应该只装一个xdg-desktop-portal实现
> 
> 安装多个不同的xdg-desktop-portal实现是没有问题的。 你的问题感觉更像是没有配置对，参考ArchWiki，xdg-desktop-portal-xapp是没有实现FileChooser的 在`/usr/share/xdg-desktop-portal/*.conf`或者`$XDG_CONFIG_HOME/xdg-desktop-portal/*.conf`里面指定一个可以用的实现+有一个可以被正常调用的文件管理器应该就正常了
> 
> * [https://wiki.archlinuxcn.org/wiki/XDG桌面门户](https://wiki.archlinuxcn.org/wiki/XDG%E6%A1%8C%E9%9D%A2%E9%97%A8%E6%88%B7)
> 
> 题外话，xdg-desktop-portal实现一大堆，支持的环境各不相同、对接口的实现有的完善有的不完善，也不太适合写到ebuild的依赖里面



> > 应该只装一个xdg-desktop-portal实现
> 
> 安装多个不同的xdg-desktop-portal实现是没有问题的。 你的问题感觉更像是没有配置对，参考ArchWiki，xdg-desktop-portal-xapp是没有实现FileChooser的 在`/usr/share/xdg-desktop-portal/*.conf`或者`$XDG_CONFIG_HOME/xdg-desktop-portal/*.conf`里面指定一个可以用的实现+有一个可以被正常调用的文件管理器应该就正常了
> 
> * [https://wiki.archlinuxcn.org/wiki/XDG桌面门户](https://wiki.archlinuxcn.org/wiki/XDG%E6%A1%8C%E9%9D%A2%E9%97%A8%E6%88%B7)
> 
> 题外话，xdg-desktop-portal实现一大堆，支持的环境各不相同、对接口的实现有的完善有的不完善，也不太适合写到ebuild的依赖里面



> > 应该只装一个xdg-desktop-portal实现
> 
> 安装多个不同的xdg-desktop-portal实现是没有问题的。 你的问题感觉更像是没有配置对，参考ArchWiki，xdg-desktop-portal-xapp是没有实现FileChooser的 在`/usr/share/xdg-desktop-portal/*.conf`或者`$XDG_CONFIG_HOME/xdg-desktop-portal/*.conf`里面指定一个可以用的实现+有一个可以被正常调用的文件管理器应该就正常了
> 
> * [https://wiki.archlinuxcn.org/wiki/XDG桌面门户](https://wiki.archlinuxcn.org/wiki/XDG%E6%A1%8C%E9%9D%A2%E9%97%A8%E6%88%B7)
> 
> 题外话，xdg-desktop-portal实现一大堆，支持的环境各不相同、对接口的实现有的完善有的不完善，也不太适合写到ebuild的依赖里面



> > 应该只装一个xdg-desktop-portal实现
> 
> 安装多个不同的xdg-desktop-portal实现是没有问题的。 你的问题感觉更像是没有配置对，参考ArchWiki，xdg-desktop-portal-xapp是没有实现FileChooser的 在`/usr/share/xdg-desktop-portal/*.conf`或者`$XDG_CONFIG_HOME/xdg-desktop-portal/*.conf`里面指定一个可以用的实现+有一个可以被正常调用的文件管理器应该就正常了
> 
> * [https://wiki.archlinuxcn.org/wiki/XDG桌面门户](https://wiki.archlinuxcn.org/wiki/XDG%E6%A1%8C%E9%9D%A2%E9%97%A8%E6%88%B7)
> 
> 题外话，xdg-desktop-portal实现一大堆，支持的环境各不相同、对接口的实现有的完善有的不完善，也不太适合写到ebuild的依赖里面

好的，感谢菊苣指教。
我也想提这个依赖的事，但是这个一大堆实现好像也确实不咋行，也没有个virtual/xdg-desktop-portal包，optfeature好像也不妥,感觉可以写一个ewarn之类的
