### ISSUE TITLE
[mirrors] 大陆镜像

### ISSUE THREAD

**Issue by EssenSea** [Gentoo-zh/gentoo-zh#5038]
这个overlay（可以，会）有大陆的镜像么？如果有的话，是否存在使用指导
刚刚安装好的gentoo，如果没有v2raya的话，都不知道怎么刷新可用的overlay list。
不知道怎么从官方仓库里施展魔法，有无大佬指教？
或者有无大佬能帮忙把v2raya打包进官方仓库

**Comment by liangyongxiang** [comment]
镜像包括两个意思，一个是仓库的镜像（包含了ebuild），一个是 distfile 的镜像。
我们有前者没有后者，前者的链接是：https://mirrors.cqu.edu.cn/#/wiki/mirror-wiki/gentoo-zh.git

**Comment by EssenSea** [comment]
> 镜像包括两个意思，一个是仓库的镜像（包含了ebuild），一个是 distfile 的镜像。 我们有前者没有后者，前者的链接是：https://mirrors.cqu.edu.cn/#/wiki/mirror-wiki/gentoo-zh.git
感谢！！！

**Comment by EssenSea** [comment]
> 镜像包括两个意思，一个是仓库的镜像（包含了ebuild），一个是 distfile 的镜像。 我们有前者没有后者，前者的链接是：https://mirrors.cqu.edu.cn/#/wiki/mirror-wiki/gentoo-zh.git

新人刚刚意识到无distfiles是什么鬼。。。现在的 正在面对 ”官仓“ 苦于 如何施展魔法（大陆网络环境），从而登录诸如本同性交友网站（程序员群体男性占据绝对主流，故戏称世界最大男性同性交友平台）等人才云集的网络平台
