### ISSUE TITLE
[request: 镜像方法] 向国内高校镜像站点提交本overlay的镜像请求

### ISSUE THREAD

**Issue by EssenSea** [Gentoo-zh/gentoo-zh#5039]
向国内高校镜像站点提交本overlay的镜像请求，镜像站点要求提供镜像方法。 不了解相关内容，请求帮助，提前感谢能够提供帮助的相关大佬。
 此外还打算提交gentoo-guru overlay 的镜像请求，同求镜像方法或相关指导

**Comment by Universebenzene** [comment]
@Essential-sea 题外话，我觉得没有distfiles的话光镜像overlay的tree本身还是解决不了多少问题。玩Linux还是备好梯子安逸

**Comment by Puqns67** [comment]
如果是镜像仓库的话直接同步这个 git 仓库就行了，如果要同步 distfiles 那就会比较麻烦了（
不同步 distfiles 的话使用起来依然需要使用代理软件，没啥意义。

**Comment by RevySR** [comment]
如果需要提交就要重新清查所有软件分发的风险问题 还有相应distfiles重分发风险
如果你有兴趣 可以先把当前仓库distfile分发全部过一遍 看看有没有什么法律风险

**Comment by EssenSea** [comment]
> 如果需要提交就要重新清查所有软件分发的风险问题 还有相应distfiles重分发风险 如果你有兴趣 可以先把当前仓库distfile分发全部过一遍 看看有没有什么法律风险

谢谢

**Comment by EssenSea** [comment]
> @Essential-sea 题外话，我觉得没有distfiles的话光镜像overlay的tree本身还是解决不了多少问题。玩Linux还是备好梯子安逸

就是冲着v2raya 提交镜像，但是目前来看如果要检查distfile 分发风险的话似乎工作量有点大

**Comment by EssenSea** [comment]
> 如果是镜像仓库的话直接同步这个 git 仓库就行了，如果要同步 distfiles 那就会比较麻烦了（ 不同步 distfiles 的话使用起来依然需要使用代理软件，没啥意义。

同步 disfile 的话有无具体方法说明，我对这一块是一点不懂，非计算机科班出身，虽然能够安装使用gentoo，但是很多东西了解很欠缺

**Comment by EssenSea** [comment]
> 如果需要提交就要重新清查所有软件分发的风险问题 还有相应distfiles重分发风险 如果你有兴趣 可以先把当前仓库distfile分发全部过一遍 看看有没有什么法律风险

能不能只提供同步方案，分发风险检查交由相关镜像站点完成.......毕竟学校里面人手组织起来要比我们组织我们这些零散人员要方便一些

**Comment by Puqns67** [comment]
> > @Essential-sea 题外话，我觉得没有distfiles的话光镜像overlay的tree本身还是解决不了多少问题。玩Linux还是备好梯子安逸
> 
> 就是冲着v2raya 提交镜像，但是目前来看如果要检查distfile 分发风险的话似乎工作量有点大

非闭源程序一般情况下都能再分发源码的，闭源软件的 bin 包的再分发风险会很大。

> > 如果是镜像仓库的话直接同步这个 git 仓库就行了，如果要同步 distfiles 那就会比较麻烦了（ 不同步 distfiles 的话使用起来依然需要使用代理软件，没啥意义。
> 
> 同步 disfile 的话有无具体方法说明，我对这一块是一点不懂，非计算机科班出身，虽然能够安装使用gentoo，但是很多东西了解很欠缺

最好要有一个中心化的服务器，用来上传 distfiles 的存档，然后上 rsync 之类方案同步就行了，但是服务器要有成本（

**Comment by EssenSea** [comment]
我是看到你们的讨论后才注意到 distfiles 的问题，看起来工作量不小

**Comment by EssenSea** [comment]
> 我是看到你们的讨论后才注意到 distfiles 的问题，看起来工作量不小

此外如果检查的话是要逐行阅读leciences 么，还是只需要注意 哪一种许可证就可以了？

**Comment by EssenSea** [comment]
> > > @Essential-sea 题外话，我觉得没有distfiles的话光镜像overlay的tree本身还是解决不了多少问题。玩Linux还是备好梯子安逸
> > 
> > 
> > 就是冲着v2raya 提交镜像，但是目前来看如果要检查distfile 分发风险的话似乎工作量有点大
> 
> 非闭源程序一般情况下都能再分发源码的，闭源软件的 bin 包的再分发风险会很大。
> 
> > > 如果是镜像仓库的话直接同步这个 git 仓库就行了，如果要同步 distfiles 那就会比较麻烦了（ 不同步 distfiles 的话使用起来依然需要使用代理软件，没啥意义。
> > 
> > 
> > 同步 disfile 的话有无具体方法说明，我对这一块是一点不懂，非计算机科班出身，虽然能够安装使用gentoo，但是很多东西了解很欠缺
> 
> 最好要有一个中心化的服务器，用来上传 distfiles 的存档，然后上 rsync 之类方案同步就行了，但是服务器要有成本（

后面一句没听懂，如果提交到高校镜像站点的话，仍然需要第三方的服务器么？ 我是指望提交一段 shell script 或者 类似的文本文件， 然后 高校镜像站点 从相应（文本中指明的）站点 同步 distfile 并存储到镜像服务器.....

**Comment by peeweep** [comment]
可以搭建一个 gentoo-zh distfiles mirror, 开放 http 和 rsync， 国内镜像以 rsync://distfiles.example.com 作为上游。
感觉最好用一个正式一点的域名，不知道 gentoo.org.cn 现在在谁手里了。

**Comment by peeweep** [comment]
https://wiki.gentoo.org/wiki/Project:Infrastructure/Mirrors/Distfile_Mirroring_System
@Essential-sea 你可以用 emirrordist 命令制作 distfiles mirror

我在 yongxiang 的服务器上托管了一个 gentoo-zh  distfiles mirror，你可以直接用。
`GENTOO_MIRRORS="${GENTOO_MIRRORS} https://distfiles.gentoocn.org"`
