### ISSUE TITLE
dev-libs/v2ray-{domain-list-community,geoip}

### ISSUE THREAD

**Issue by blackteahamburger** [Gentoo-zh/gentoo-zh#5066]
- 当前的 dev-libs/v2ray-domain-list-community 是旧的并且无人维护，做了个新的：https://github.com/blackteahamburger/qv2ray-overlay/tree/master/dev-libs/v2ray-domain-list-community.
- 新的 [dev-libs/v2ray-geoip](https://github.com/blackteahamburger/qv2ray-overlay/tree/master/dev-libs/v2ray-geoip)，由于许可证限制需要自己下载 GeoLite2-Country-CSV.zip（见 https://github.com/v2fly/geoip?tab=readme-ov-file#notices ），为避免校验以允许使用更新版本的文件没有写在 SRC_URI 里。
- 需要 virtual/v2ray-{domain-list-community,geoip} 解决 app-alternatives/v2ray-geo{ip,site}[v2fly] 的依赖

**Comment by EssenSea** [comment]
net-proxy/v2ray and net-proxy/v2ray-bin is still depend on app-alternatives/v2tay-geo{ip,site} in their (v2ray's) ebuild file,  and can not be used, caused by GeoLite2-Country-CSV.zip cannot be download . Please consider change v2ray's depend in ebuild.
