### ISSUE TITLE
net-misc/rustdesk doexe failed

### ISSUE THREAD

**Issue by xiecanlin** [Gentoo-zh/gentoo-zh#5214]
>>> Install net-misc/rustdesk-1.2.6 into /var/tmp/portage/net-misc/rustdesk-1.2.6/image
!!! doexe: target/release/rustdesk does not exist
 * ERROR: net-misc/rustdesk-1.2.6::gentoo-zh failed (install phase):
 *   doexe failed
 *
 * If you need support, post the output of `emerge --info '=net-misc/rustdesk-1.2.6::gentoo-zh'`,
 * the complete build log and the output of `emerge -pqv '=net-misc/rustdesk-1.2.6::gentoo-zh'`.
 * The complete build log is located at '/var/tmp/portage/net-misc/rustdesk-1.2.6/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/net-misc/rustdesk-1.2.6/temp/environment'.
 * Working directory: '/var/tmp/portage/net-misc/rustdesk-1.2.6/work/rustdesk-1.2.6'
 * S: '/var/tmp/portage/net-misc/rustdesk-1.2.6/work/rustdesk-1.2.6'
 * QA Notice: file does not exist:
 *
 *      doexe: target/release/rustdesk does not exist

**Comment by peeweep** [comment]
可以用 `$(cargo_target_dir)` 替代 `target/release`，参考 1f6ce98b70f1ca691b1770e2b24463c62613a8d2 。
我试着编译了一下编不过，报错太多了，等一个好心人去修吧。

**Comment by xiecanlin** [comment]
> 可以用 `$(cargo_target_dir)` 替代 `target/release`，参考 [1f6ce98](https://github.com/microcai/gentoo-zh/commit/1f6ce98b70f1ca691b1770e2b24463c62613a8d2) 。 我试着编译了一下编不过，报错太多了，等一个好心人去修吧。

谢谢，安装通过了
