### ISSUE TITLE
clash-verge-bin: no such file or directory (os error2)

### ISSUE THREAD

**Issue by gouwazi** [Gentoo-zh/gentoo-zh#5310]
clash-verge-rev 查找内核的路径是/usr/bin/verge-mihomo和/usr/bin/verge-mihomo-alpha
mihomo的ebuild里面只有一个软连接 /usr/bin/clash-meta -> /usr/bin/mihomo

我添加了一个软连接/usr/bin/verge-mihomo -> /usr/bin/mihomo 就ok了

那么这个软连接放在mihomo的ebuild里面还是clash-verge-bin的ebuild里面呢？

**Comment by liangyongxiang** [comment]
clash-verge-bin的ebuild里面吧。如果是有多个软件有类似的需求倒是可以考虑在 mihomo 里面处理。
