### ISSUE TITLE
net-misc/todesk: libappindicator requirements

### ISSUE THREAD

**Issue by mawwalker** [Gentoo-zh/gentoo-zh#5588]
Gentoo removed libappindicator3.

I Tried dev-libs/libayatana-appindicator and replace libayatana-appindicator3.so.1.0.0 as libappindicator3.so.1.0.0

And it works

So, Please Try to use dev-libs/libayatana-appindicator as the depends in ebuild

**Comment by peeweep** [comment]
试一下 todesk-4.7.2.0-r1

**Comment by mawwalker** [comment]
> 试一下 todesk-4.7.2.0-r1

这样命名版本号会导致下载deb失败

**Comment by irort** [comment]
> > 试一下 todesk-4.7.2.0-r1
> 
> 这样命名版本号会导致下载deb失败

不会，PV不会包含后面的-r1, 详细见 https://devmanual.gentoo.org/ebuild-writing/variables/index.html

**Comment by peeweep** [comment]
可能是 dl.todesk.com 配置的防火墙规则禁止了你用 wget 下载， https://dl.todesk.com/linux/todesk-v4.7.2.0-amd64.deb 在浏览器手动下载然后复制到 /var/cache/distfiles/todesk-v4.7.2.0-amd64.deb 吧。

![图片](https://github.com/user-attachments/assets/dbea7990-ba86-4086-a7da-f3d909fa8129)

**Comment by mawwalker** [comment]
已解决，感谢
