### ISSUE TITLE
Additional Package Request: media-fonts/shanggu

### ISSUE THREAD

**Issue by ghost** [Gentoo-zh/gentoo-zh#5648]
Shanggu is an [open source](https://github.com/GuiWonder/Shanggu/blob/main/LICENSE.txt) CJK font that uses traditional letterforms; (_jiù zìxíng_/_kyūjitai_) a fork of [Noto CJK](https://github.com/notofonts/noto-cjk).

Upstream URL: https://github.com/GuiWonder/Shanggu

---

I have tried to create my own ebuild, but it is archived in 7zip and cannot be expanded.

How can I extract 7zip with ebuild?

**Comment by peeweep** [comment]
you can use `inherit unpacker` , [unpacker.eclass](https://devmanual.gentoo.org/eclass-reference/unpacker.eclass/index.html) will auto extract .7z distfiles, for example [tcl3d-0.9.5.ebuild](https://github.com/gentoo/gentoo/blob/9462d10fa71e59e542e520a1a6bb56e220ba7d61/dev-tcltk/tcl3d/tcl3d-0.9.5.ebuild#L6)
