### ISSUE TITLE
app-i18n/mozc-2.30.5544.102: package bump

### ISSUE THREAD

**Issue by ghost** [Gentoo-zh/gentoo-zh#5876]
Version 2.30.5544.102 is released.
https://github.com/google/mozc/releases/tag/2.30.5544.102

**Comment by liangyongxiang** [comment]
gentoo-zh copied mozc from the main tree to support fcitx-5. 
So now it can be removed from gentoo-zh. 
We should submit a request at bugs.gentoo.org.

**Comment by liangyongxiang** [comment]
https://bugs.gentoo.org/943518

**Comment by liangyongxiang** [comment]
I'll close this bug for now. Please feel free to open it.
